/* hl.c — Run static aarch64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2025 Moritz Angermann <moritz@zw3rk.com>, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *
 * Usage: hl [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */
#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "guest.h"
#include "elf.h"
#include "syscall.h"
#include "syscall_internal.h"  /* LINUX_PATH_MAX (for elf_path realpath) */
#include "syscall_proc.h"
#include "fork_ipc.h"
#include "stack.h"

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* ---------- Helpers ---------- */

/* Resolve interpreter path against a sysroot.  Tries three strategies:
 *   1. sysroot + interp_path  (works for /lib/ld-musl-*.so.1)
 *   2. sysroot + "/lib/" + basename(interp_path)  (handles nix store paths
 *      like /nix/store/...-musl-1.2.5/lib/ld-musl-aarch64.so.1)
 *   3. interp_path as-is  (no sysroot, or all fallbacks failed)
 * Returns the resolved path in `out` (must be LINUX_PATH_MAX bytes). */
static void resolve_interp(const char *sysroot, const char *interp_path,
                            char *out, size_t out_sz) {
    if (sysroot) {
        /* Strategy 1: sysroot + full interp path */
        snprintf(out, out_sz, "%s%s", sysroot, interp_path);
        if (access(out, F_OK) == 0)
            return;

        /* Strategy 2: sysroot/lib/basename — handles nix store paths */
        const char *base = strrchr(interp_path, '/');
        base = base ? base + 1 : interp_path;
        snprintf(out, out_sz, "%s/lib/%s", sysroot, base);
        if (access(out, F_OK) == 0)
            return;

        /* Fall through to raw path */
    }
    strncpy(out, interp_path, out_sz - 1);
    out[out_sz - 1] = '\0';
}

#define HV_CHECK(call) do {                                        \
    hv_return_t _r = (call);                                       \
    if (_r != HV_SUCCESS) {                                        \
        fprintf(stderr, "hl: %s failed: %d\n", #call, (int)_r);   \
        exit(1);                                                   \
    }                                                              \
} while (0)

/* ---------- TCR_EL1 ---------- */

/* TCR_EL1 for 4KB granule, 48-bit VA:
 *   T0SZ  = 16  (48-bit TTBR0 VA space)
 *   IRGN0 = WB RA WA, ORGN0 = WB RA WA, SH0 = Inner Shareable
 *   TG0   = 4KB
 *   T1SZ  = 16  (48-bit, valid even though EPD1 disables walks)
 *   EPD1  = 1   (DISABLE TTBR1 walks — we don't use the upper VA space)
 *   IRGN1 = WB RA WA, ORGN1 = WB RA WA, SH1 = Inner Shareable
 *   TG1   = 4KB (encoding 0b10)
 *   IPS   = 48-bit PA (0b101)
 *
 * Bit layout:
 *   [5:0]   T0SZ   = 0x10
 *   [7]     EPD0   = 0
 *   [9:8]   IRGN0  = 0b01
 *   [11:10] ORGN0  = 0b01
 *   [13:12] SH0    = 0b11
 *   [15:14] TG0    = 0b00
 *   [21:16] T1SZ   = 0x10
 *   [22]    A1     = 0
 *   [23]    EPD1   = 1      ← changed from old value (was 0)
 *   [25:24] IRGN1  = 0b01
 *   [27:26] ORGN1  = 0b01
 *   [29:28] SH1    = 0b11
 *   [31:30] TG1    = 0b10
 *   [34:32] IPS    = 0b101
 */
#define TCR_EL1_VALUE 0x5B5903510ULL

/* ---------- SCTLR_EL1 bits ---------- */
#define SCTLR_M   (1ULL << 0)   /* MMU enable */
#define SCTLR_C   (1ULL << 2)   /* Data cache enable */
#define SCTLR_I   (1ULL << 12)  /* Instruction cache enable */

/* RES1 bits in SCTLR_EL1 — these MUST be 1 for correct behaviour.
 * Apple Hypervisor.framework returns default SCTLR=0x0, so we must set
 * them explicitly.  The hardware eventually auto-updates them, but the
 * initial instruction fetches execute with whatever we wrote. */
#define SCTLR_RES1 ((1ULL << 29) /* LSMAOE */  | \
                     (1ULL << 28) /* nTLSMD */  | \
                     (1ULL << 23) /* SPAN   */  | \
                     (1ULL << 22) /* EIS    */  | \
                     (1ULL << 20) /* TSCXT  */  | \
                     (1ULL << 11) /* EOS    */  | \
                     (1ULL <<  8) /* SED    */  | \
                     (1ULL <<  7) /* ITD    */)

/* ---------- Main ---------- */

int main(int argc, const char **argv) {
    int verbose = 0;
    int timeout_sec = 10;  /* Default: 10 second timeout */
    int fork_child_fd = -1; /* IPC fd for --fork-child mode */
    const char *sysroot = NULL; /* Sysroot for dynamic linker resolution */
    int arg_start = 1;

    /* Parse hl options */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (strcmp(argv[arg_start], "--verbose") == 0 ||
            strcmp(argv[arg_start], "-v") == 0) {
            verbose = 1;
            arg_start++;
        } else if ((strcmp(argv[arg_start], "--timeout") == 0 ||
                    strcmp(argv[arg_start], "-t") == 0) &&
                   arg_start + 1 < argc) {
            timeout_sec = atoi(argv[arg_start + 1]);
            if (timeout_sec <= 0) timeout_sec = 10;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--fork-child") == 0 &&
                   arg_start + 1 < argc) {
            fork_child_fd = atoi(argv[arg_start + 1]);
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--sysroot") == 0 &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--") == 0) {
            arg_start++;
            break;
        } else {
            fprintf(stderr, "hl: unknown option: %s\n", argv[arg_start]);
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, verbose, timeout_sec);

    if (arg_start >= argc) {
        fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                "[--sysroot PATH] <elf-path> [args...]\n");
        return 1;
    }

    const char *elf_path = argv[arg_start];
    int guest_argc = argc - arg_start;
    const char **guest_argv = &argv[arg_start];

    /* ---- Step 1: Load and parse ELF ---- */
    elf_info_t elf_info;
    if (elf_load(elf_path, &elf_info) < 0) {
        fprintf(stderr, "hl: failed to load ELF: %s\n", elf_path);
        return 1;
    }

    if (verbose) {
        fprintf(stderr, "hl: ELF entry=0x%llx, %d segments, "
                "load range [0x%llx, 0x%llx)\n",
                (unsigned long long)elf_info.entry,
                elf_info.num_segments,
                (unsigned long long)elf_info.load_min,
                (unsigned long long)elf_info.load_max);
    }

    /* ---- Step 2: Initialize guest memory and VM ---- */
    guest_t g;
    if (guest_init(&g, GUEST_MEM_SIZE) < 0) {
        fprintf(stderr, "hl: failed to initialize guest\n");
        return 1;
    }

    /* ---- Step 3: Load ELF segments into guest memory ---- */
    /* PIE executables (ET_DYN) have virtual addresses starting near 0,
     * which would overlap with the page table pool and shim. Load them
     * at PIE_LOAD_BASE (0x400000) instead. ET_EXEC binaries already
     * have absolute addresses (typically 0x400000+), so use base 0. */
    uint64_t elf_load_base = (elf_info.e_type == ET_DYN) ? PIE_LOAD_BASE : 0;

    if (elf_map_segments(&elf_info, elf_path,
                         g.host_base, g.guest_size, elf_load_base) < 0) {
        fprintf(stderr, "hl: failed to map ELF segments\n");
        guest_destroy(&g);
        return 1;
    }

    /* Set brk base after the highest loaded segment */
    uint64_t brk_start = (elf_info.load_max + elf_load_base + 4095) & ~4095ULL;
    if (brk_start < BRK_BASE_DEFAULT)
        brk_start = BRK_BASE_DEFAULT;
    g.brk_base = brk_start;
    g.brk_current = brk_start;

    /* ---- Step 3b: Load dynamic linker if PT_INTERP present ---- */
    elf_info_t interp_info;
    uint64_t interp_base = 0;
    memset(&interp_info, 0, sizeof(interp_info));

    if (elf_info.interp_path[0] != '\0') {
        /* Resolve interpreter path, applying sysroot if set */
        char interp_resolved[LINUX_PATH_MAX];
        resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        if (verbose)
            fprintf(stderr, "hl: loading interpreter: %s\n", interp_resolved);

        if (elf_load(interp_resolved, &interp_info) < 0) {
            fprintf(stderr, "hl: failed to load interpreter: %s\n",
                    interp_resolved);
            guest_destroy(&g);
            return 1;
        }

        /* Load interpreter at INTERP_LOAD_BASE (ET_DYN at chosen base) */
        interp_base = INTERP_LOAD_BASE;
        if (elf_map_segments(&interp_info, interp_resolved,
                             g.host_base, g.guest_size, interp_base) < 0) {
            fprintf(stderr, "hl: failed to map interpreter segments\n");
            guest_destroy(&g);
            return 1;
        }

        if (verbose) {
            fprintf(stderr, "hl: interpreter loaded at base=0x%llx, "
                    "entry=0x%llx, %d segments\n",
                    (unsigned long long)interp_base,
                    (unsigned long long)(interp_info.entry + interp_base),
                    interp_info.num_segments);
        }
    }

    /* ---- Step 4: Load shim into guest at SHIM_BASE ---- */
    if (shim_bin_len > BLOCK_2MB) {
        fprintf(stderr, "hl: shim binary too large (%u bytes)\n", shim_bin_len);
        guest_destroy(&g);
        return 1;
    }
    memcpy((uint8_t *)g.host_base + SHIM_BASE, shim_bin, shim_bin_len);

    if (verbose) {
        fprintf(stderr, "hl: shim loaded at offset 0x%llx (%u bytes)\n",
                (unsigned long long)SHIM_BASE, shim_bin_len);
    }

    /* ---- Step 5: Build page tables ---- */
    #define MAX_REGIONS 32
    mem_region_t regions[MAX_REGIONS];
    int nregions = 0;

    /* NOTE: Page table pool is NOT mapped in stage-1 page tables.
     * The MMU hardware walker accesses page tables through stage-2
     * translation (hv_vm_map RWX), so stage-1 mapping is unnecessary.
     * This avoids merging PT pool's RW perms with shim code's RX perms
     * in the same 2MB block, keeping the shim code block as RX. */

    /* Shim code (RX) — sized to just cover the actual binary.
     * IMPORTANT: Apple HVF enforces W^X even with SCTLR.WXN=0.
     * This region must NOT overlap with any RW region in the same
     * 2MB block, or the merged RWX permissions will cause faults. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_BASE,
        .gpa_end   = SHIM_BASE + shim_bin_len,
        .perms     = MEM_PERM_RX
    };

    /* Shim data/stack (RW) */
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_DATA_BASE,
        .gpa_end   = SHIM_DATA_BASE + BLOCK_2MB,
        .perms     = MEM_PERM_RW
    };

    /* ELF segments: map each based on its p_flags.
     * Segment GPAs from elf_load() are raw virtual addresses; add
     * elf_load_base (non-zero for PIE) to match where elf_map_segments
     * actually placed the data. */
    for (int i = 0; i < elf_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (elf_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (elf_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        regions[nregions++] = (mem_region_t){
            .gpa_start = elf_info.segments[i].gpa + elf_load_base,
            .gpa_end   = elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
            .perms     = perms
        };
    }

    /* Interpreter segments (if dynamic linking) */
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (interp_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (interp_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        regions[nregions++] = (mem_region_t){
            .gpa_start = interp_info.segments[i].gpa + interp_base,
            .gpa_end   = interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
            .perms     = perms
        };
    }

    /* brk region (RW) */
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.brk_base,
        .gpa_end   = MMAP_BASE,
        .perms     = MEM_PERM_RW
    };

    /* Stack (RW) */
    regions[nregions++] = (mem_region_t){
        .gpa_start = STACK_BASE,
        .gpa_end   = STACK_TOP,
        .perms     = MEM_PERM_RW
    };

    /* mmap RW region (pre-mapped up to MMAP_INITIAL_END).
     * Additional pages beyond this are mapped dynamically by
     * guest_extend_page_tables() when sys_mmap needs more space. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_BASE,
        .gpa_end   = MMAP_INITIAL_END,
        .perms     = MEM_PERM_RW
    };
    g.mmap_end = MMAP_INITIAL_END;

    /* mmap RX region (separate 2MB blocks for PROT_EXEC allocations).
     * Apple HVF enforces W^X on page table entries: a 2MB block can't be
     * both writable and executable. Shared library text (PROT_EXEC) goes
     * here, separate from RW data in the main mmap region above. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_RX_BASE,
        .gpa_end   = MMAP_RX_INITIAL_END,
        .perms     = MEM_PERM_RX
    };
    g.mmap_rx_end = MMAP_RX_INITIAL_END;

    uint64_t ttbr0 = guest_build_page_tables(&g, regions, nregions);
    if (!ttbr0) {
        fprintf(stderr, "hl: failed to build page tables\n");
        guest_destroy(&g);
        return 1;
    }

    /* ---- Step 5b: Record semantic regions for /proc/self/maps ---- */
    guest_region_add(&g, SHIM_BASE, SHIM_BASE + shim_bin_len,
                     LINUX_PROT_READ | LINUX_PROT_EXEC, LINUX_MAP_PRIVATE,
                     0, "[shim]");
    guest_region_add(&g, SHIM_DATA_BASE, SHIM_DATA_BASE + BLOCK_2MB,
                     LINUX_PROT_READ | LINUX_PROT_WRITE, LINUX_MAP_PRIVATE,
                     0, "[shim-data]");

    /* Resolve ELF path for region names */
    char elf_realpath[LINUX_PATH_MAX];
    if (!realpath(elf_path, elf_realpath))
        strncpy(elf_realpath, elf_path, sizeof(elf_realpath) - 1);

    for (int i = 0; i < elf_info.num_segments; i++) {
        int prot = LINUX_PROT_READ;
        if (elf_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
        if (elf_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
        guest_region_add(&g, elf_info.segments[i].gpa + elf_load_base,
                         elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                         prot, LINUX_MAP_PRIVATE,
                         elf_info.segments[i].offset, elf_realpath);
    }

    /* Interpreter semantic regions (if dynamic linking) */
    if (interp_info.num_segments > 0) {
        char interp_resolved[LINUX_PATH_MAX];
        resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        for (int i = 0; i < interp_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (interp_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (interp_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g,
                             interp_info.segments[i].gpa + interp_base,
                             interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
                             prot, LINUX_MAP_PRIVATE,
                             interp_info.segments[i].offset, interp_resolved);
        }
    }

    /* Heap starts at brk_base (initially empty, grows via sys_brk) */
    if (g.brk_base < g.brk_current) {
        guest_region_add(&g, g.brk_base, g.brk_current,
                         LINUX_PROT_READ | LINUX_PROT_WRITE,
                         LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                         0, "[heap]");
    }

    guest_region_add(&g, STACK_BASE, STACK_TOP,
                     LINUX_PROT_READ | LINUX_PROT_WRITE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack]");

    if (verbose) {
        fprintf(stderr, "hl: TTBR0=0x%llx, IPA base=0x%llx\n",
                (unsigned long long)ttbr0, (unsigned long long)g.ipa_base);

        /* Dump page table structure */
        uint64_t l0_off = ttbr0 - g.ipa_base;
        uint64_t *l0 = (uint64_t *)((uint8_t *)g.host_base + l0_off);
        unsigned l0i = (unsigned)(g.ipa_base / (512ULL * 1024 * 1024 * 1024));
        fprintf(stderr, "hl: L0[%u]=0x%llx\n", l0i,
                (unsigned long long)l0[l0i]);

        uint64_t l1_ipa = l0[l0i] & 0xFFFFFFFFF000ULL;
        uint64_t *l1 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l1_ipa - g.ipa_base));
        unsigned l1i = (unsigned)((g.ipa_base % (512ULL * 1024 * 1024 * 1024))
                                  / (1024ULL * 1024 * 1024));
        fprintf(stderr, "hl: L1[%u]=0x%llx\n", l1i,
                (unsigned long long)l1[l1i]);

        uint64_t l2_ipa = l1[l1i] & 0xFFFFFFFFF000ULL;
        uint64_t *l2 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l2_ipa - g.ipa_base));
        for (int i = 0; i < 16; i++) {
            if (l2[i])
                fprintf(stderr, "hl: L2[%d]=0x%llx\n", i,
                        (unsigned long long)l2[i]);
        }
    }

    /* ---- Step 6: Build Linux initial stack ---- */
    syscall_init();
    proc_init();
    proc_set_shim(shim_bin, shim_bin_len);
    proc_set_elf_path(elf_path);
    proc_set_cmdline(guest_argc, guest_argv);
    if (sysroot)
        proc_set_sysroot(sysroot);
    extern const char **environ;
    uint64_t sp = build_linux_stack(&g, STACK_TOP,
                                    guest_argc, guest_argv,
                                    environ, &elf_info,
                                    elf_load_base, interp_base);

    /* Entry point: interpreter entry if dynamic, ELF entry if static.
     * For PIE (ET_DYN), elf_info.entry is relative, needs elf_load_base. */
    uint64_t entry_point = (interp_base != 0)
        ? (interp_info.entry + interp_base)
        : (elf_info.entry + elf_load_base);

    if (verbose) {
        fprintf(stderr, "hl: SP=0x%llx, entry=0x%llx%s\n",
                (unsigned long long)sp,
                (unsigned long long)entry_point,
                interp_base ? " (via interpreter)" : "");
    }

    /* ---- Step 7: Create vCPU and configure registers ---- */
    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    HV_CHECK(hv_vcpu_create(&vcpu, &vexit, NULL));
    g.vcpu = vcpu;
    g.exit = vexit;

    /* All guest-visible addresses are IPA-based: GUEST_IPA_BASE + offset */
    uint64_t shim_ipa  = guest_ipa(&g, SHIM_BASE);
    uint64_t entry_ipa = guest_ipa(&g, entry_point);
    uint64_t sp_ipa    = guest_ipa(&g, sp);
    uint64_t el1_sp    = guest_ipa(&g, SHIM_DATA_BASE + BLOCK_2MB);

    /* -- System registers (all set from host, no HVC #4 in shim) -- */

    /* VBAR_EL1: vector table at shim_base + 0x800 (.align 11 offset) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_VBAR_EL1,
                                 shim_ipa + 0x800));

    /* MAIR_EL1: Attr0=Device-nGnRnE (0x00), Attr1=Normal WB (0xFF) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_MAIR_EL1, 0xFF00));

    /* TCR_EL1: 4KB granule, 48-bit VA, EPD1=1 (disable TTBR1 walks) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TCR_EL1, TCR_EL1_VALUE));

    /* TTBR0_EL1: page table base (IPA from guest_build_page_tables) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR0_EL1, ttbr0));

    /* TTBR1_EL1: unused (EPD1=1 disables walks) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR1_EL1, 0));

    /* CPACR_EL1: enable FP/SIMD at EL0 and EL1 (FPEN=0b11) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_CPACR_EL1, 3ULL << 20));

    /* ELR_EL1: EL0 entry point (shim will ERET to this address) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_ELR_EL1, entry_ipa));

    /* SPSR_EL1: EL0t, AArch64, all interrupts masked on entry */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SPSR_EL1, 0x0));

    /* SP_EL0: initial stack pointer for EL0 */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL0, sp_ipa));

    /* SP_EL1: EL1 stack for exception handlers (top of shim data region) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL1, el1_sp));

    /* SCTLR_EL1: read default, then enable MMU + caches */
    uint64_t sctlr;
    HV_CHECK(hv_vcpu_get_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, &sctlr));
    if (verbose)
        fprintf(stderr, "hl: SCTLR_EL1 default=0x%llx\n",
                (unsigned long long)sctlr);

    /* Build a proper SCTLR with RES1 bits + caches, but WITHOUT MMU enable.
     * Apple's HVF requires the MMU to be enabled DURING vCPU execution
     * (via HVC #4 from the shim), not before hv_vcpu_run. Setting SCTLR.M=1
     * via hv_vcpu_set_sys_reg before start causes permission faults.
     * The shim will HVC #4 to enable M after TLBI/DSB/ISB. */
    sctlr = SCTLR_RES1 | SCTLR_C | SCTLR_I;  /* No SCTLR_M here */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, sctlr));

    /* -- General purpose registers -- */

    /* PC = shim entry (TLBI + zero regs + ERET) */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_PC, shim_ipa));

    /* CPSR = EL1h (0x3c5) — shim runs at EL1 */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_CPSR, 0x3c5));

    /* Zero all general purpose registers */
    for (int i = 0; i < 31; i++) {
        HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0 + i, 0));
    }

    /* Pass the full SCTLR value (WITH M=1) in X0 for the shim to
     * enable the MMU during execution via HVC #4. */
    uint64_t sctlr_with_mmu = SCTLR_RES1 | SCTLR_M | SCTLR_C | SCTLR_I;
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0, sctlr_with_mmu));

    if (verbose) {
        fprintf(stderr, "hl: vCPU configured: PC=0x%llx SCTLR=0x%llx "
                "VBAR=0x%llx TTBR0=0x%llx TCR=0x%llx\n",
                (unsigned long long)shim_ipa,
                (unsigned long long)sctlr,
                (unsigned long long)(shim_ipa + 0x800),
                (unsigned long long)ttbr0,
                (unsigned long long)TCR_EL1_VALUE);
        fprintf(stderr, "hl: ELR_EL1=0x%llx SP_EL0=0x%llx SP_EL1=0x%llx\n",
                (unsigned long long)entry_ipa,
                (unsigned long long)sp_ipa,
                (unsigned long long)el1_sp);
    }

    /* ---- Step 8: vCPU execution loop ---- */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec);

    /* ---- Cleanup ---- */
    guest_destroy(&g);

    return exit_code;
}
