/* hl.c — Run aarch64-linux and x86_64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2025 Moritz Angermann <moritz@zw3rk.com>, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *   - x86_64-linux support via Apple's Rosetta Linux translator, which
 *     JIT-translates x86_64 instructions to ARM64 syscalls transparently.
 *
 * Usage: hl [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */
#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/sysctl.h>
#include <libkern/OSCacheControl.h>
#include <mach-o/dyld.h>

#include "guest.h"
#include "elf.h"
#include "syscall.h"
#include "syscall_internal.h"  /* LINUX_PATH_MAX (for elf_path realpath) */
#include "syscall_proc.h"
#include "hv_util.h"
#include "fork_ipc.h"
#include "stack.h"
#include "vdso.h"
#include "thread.h"
#include "rosetta.h"
#include "gdb_stub.h"

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* Build-time version string (generated by make into _build/version.h) */
#include "version.h"

/* ---------- Main ---------- */

int main(int argc, char **argv) {
    int verbose = 0;
    int timeout_sec = 10;  /* Default: 10 second timeout */
    int fork_child_fd = -1; /* IPC fd for --fork-child mode */
    const char *sysroot = NULL; /* Sysroot for dynamic linker resolution */
    int gdb_port = 0;         /* GDB RSP port (0 = disabled) */
    int gdb_stop_on_entry = 0; /* Wait for GDB attach before executing */
    int arg_start = 1;

    /* Handle --version / --help before option parsing */
    if (argc > 1) {
        if (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-V") == 0) {
            printf("hl %s\n", HL_VERSION);
            return 0;
        }
        if (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
            /* Locate man page relative to binary.  execlp replaces the
             * process, so we must check access() before each attempt —
             * once man(1) runs, there is no fallback. */
            char man_path[4096];
            const char *slash = strrchr(argv[0], '/');
            if (slash) {
                int dirlen = (int)(slash - argv[0]);
                /* Installed: <bindir>/../share/man/man1/hl.1 */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../share/man/man1/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Source tree: <bindir>/../hl.1  (binary in _build/) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Distribution zip: <bindir>/hl.1  (binary and man page side by side) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
            }
            /* System man path (last resort — replaces process) */
            execlp("man", "man", "1", "hl", (char *)NULL);
            /* man not available at all */
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] [--gdb PORT] "
                    "[--gdb-stop-on-entry] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Parse hl options */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (strcmp(argv[arg_start], "--verbose") == 0 ||
            strcmp(argv[arg_start], "-v") == 0) {
            verbose = 1;
            hl_verbose = 1;  /* Global flag for detached threads */
            arg_start++;
        } else if ((strcmp(argv[arg_start], "--timeout") == 0 ||
                    strcmp(argv[arg_start], "-t") == 0) &&
                   arg_start + 1 < argc) {
            timeout_sec = atoi(argv[arg_start + 1]);
            if (timeout_sec <= 0) timeout_sec = 10;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--fork-child") == 0 &&
                   arg_start + 1 < argc) {
            fork_child_fd = atoi(argv[arg_start + 1]);
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--sysroot") == 0 &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--gdb") == 0 &&
                   arg_start + 1 < argc) {
            gdb_port = atoi(argv[arg_start + 1]);
            if (gdb_port <= 0 || gdb_port > 65535) {
                fprintf(stderr, "hl: invalid GDB port: %s\n",
                        argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--gdb-stop-on-entry") == 0) {
            gdb_stop_on_entry = 1;
            arg_start++;
        } else if (strcmp(argv[arg_start], "--") == 0) {
            arg_start++;
            break;
        } else {
            fprintf(stderr, "hl: unknown option: %s\n", argv[arg_start]);
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] [--gdb PORT] "
                    "[--gdb-stop-on-entry] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, verbose, timeout_sec);

    if (arg_start >= argc) {
        fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                "[--sysroot PATH] <elf-path> [args...]\n");
        return 1;
    }

    /* Copy elf_path and guest_argv to heap — the original argv string data
     * lives in a contiguous stack region that we clobber below for the
     * process title (PostgreSQL/nginx argv-clobber technique). */
    const char *elf_path = strdup(argv[arg_start]);
    int guest_argc = argc - arg_start;
    const char **guest_argv = malloc(guest_argc * sizeof(char *));
    for (int i = 0; i < guest_argc; i++)
        guest_argv[i] = strdup(argv[arg_start + i]);

    /* ---- Step 1: Load and parse ELF ---- */
    elf_info_t elf_info;
    if (elf_load(elf_path, &elf_info) < 0) {
        fprintf(stderr, "hl: failed to load ELF: %s\n", elf_path);
        return 1;
    }

    if (verbose) {
        fprintf(stderr, "hl: ELF entry=0x%llx, %d segments, "
                "load range [0x%llx, 0x%llx), machine=%s\n",
                (unsigned long long)elf_info.entry,
                elf_info.num_segments,
                (unsigned long long)elf_info.load_min,
                (unsigned long long)elf_info.load_max,
                elf_info.e_machine == EM_AARCH64 ? "aarch64" : "x86_64");
    }

    /* ---- Step 1b: Detect x86_64 ---- */
    int need_rosetta = (elf_info.e_machine == EM_X86_64);
    rosetta_result_t rr;
    memset(&rr, 0, sizeof(rr));

    /* ---- Step 2: Initialize guest memory and VM ---- */
    /* For rosetta mode, request 48-bit IPA even on M2 (which defaults to
     * 36-bit). This gives a 1TB primary buffer (buf_bits = min(48, 40) = 40)
     * instead of 64GB, providing ~1008GB of mmap backing space for rosetta's
     * high-VA JIT allocations that would otherwise exhaust the 48GB M2 pool.
     * The VM's Stage-2 IPA width also needs 48-bit for rosetta's page tables
     * to map VAs above 64GB (e.g., PIE base at 85TB). For native aarch64,
     * auto-detect (36/40-bit) is sufficient. */
    guest_t g;
    if (guest_init(&g, 0, need_rosetta ? 48 : 0) < 0) {
        fprintf(stderr, "hl: failed to initialize guest\n");
        return 1;
    }
    g.is_rosetta = need_rosetta;
    g.verbose = verbose;

    /* Set process title so ps/Activity Monitor show the guest binary name
     * instead of "hl" (e.g. "grep (x86_64-linux)").
     *
     * Three mechanisms (following PostgreSQL/nginx convention):
     * - argv[0] clobber: macOS ps reads live from KERN_PROCARGS2, so
     *   overwriting the contiguous argv+environ area on the stack changes
     *   what `ps -o comm` and `ps -o args` display.
     * - kern.procname sysctl: writes the kernel p_name field (pbi_name),
     *   which Activity Monitor reads via proc_pidinfo(PROC_PIDTBSDINFO).
     * - setprogname: updates libc getprogname() and crash reports.
     * - pthread_setname_np: sets main thread name (Instruments, lldb). */
    {
        const char *slash = strrchr(elf_path, '/');
        const char *bin = slash ? slash + 1 : elf_path;
        const char *arch = need_rosetta ? "x86_64" : "aarch64";
        char title[256];
        snprintf(title, sizeof(title), "%s (%s-linux)", bin, arch);

        /* Write kernel p_name (up to 2*MAXCOMLEN=32 chars) so Activity
         * Monitor picks up the guest binary name. setprogname() only
         * sets the libc-internal __progname and does NOT touch the kernel. */
        sysctlbyname("kern.procname", NULL, NULL, title, strlen(title));
        setprogname(title);

        char thread_name[64];
        snprintf(thread_name, sizeof(thread_name), "%s (%s-linux)",
                 bin, arch);
        pthread_setname_np(thread_name);

        /* Clobber argv[0] with the new title. On macOS, argv and environ
         * strings are contiguous on the stack. We compute the total available
         * buffer from argv[0] through the end of the last environ string,
         * copy environ to the heap first (so getenv() keeps working), then
         * overwrite the entire region with our title. */
        extern char **environ;
        if (argv[0] != NULL && environ != NULL) {
            /* Find the end of the contiguous argv+environ area */
            char *argv_end = argv[0];
            for (int i = 0; i < argc; i++) {
                if (argv[i] != NULL) {
                    char *p = argv[i] + strlen(argv[i]) + 1;
                    if (p > argv_end) argv_end = p;
                }
            }
            for (int i = 0; environ[i] != NULL; i++) {
                char *p = environ[i] + strlen(environ[i]) + 1;
                if (p > argv_end) argv_end = p;
            }
            size_t avail = (size_t)(argv_end - argv[0]);

            /* Copy environ to heap so getenv() survives the clobber */
            int env_count = 0;
            while (environ[env_count]) env_count++;
            char **new_environ = malloc((env_count + 1) * sizeof(char *));
            if (new_environ) {
                for (int i = 0; i < env_count; i++)
                    new_environ[i] = strdup(environ[i]);
                new_environ[env_count] = NULL;
                environ = new_environ;
            }

            /* Write title into the original argv area */
            size_t title_len = strlen(title);
            if (title_len < avail) {
                memcpy(argv[0], title, title_len);
                memset(argv[0] + title_len, '\0', avail - title_len);
            }
            /* Null out remaining argv pointers so ps doesn't show stale args */
            for (int i = 1; i < argc; i++)
                argv[i] = NULL;
        }
    }

    if (verbose) {
        fprintf(stderr, "hl: IPA size: %u bits (%lluGB primary)\n",
                g.ipa_bits,
                (unsigned long long)(g.guest_size / (1024ULL * 1024 * 1024)));
    }

    /* ---- Step 3: Load ELF segments into guest memory ---- */
    /* PIE executables (ET_DYN) have virtual addresses starting near 0,
     * which would overlap with the page table pool and shim. Load them
     * at PIE_LOAD_BASE (0x400000) instead. ET_EXEC binaries already
     * have absolute addresses (typically 0x400000+), so use base 0. */
    uint64_t elf_load_base = (elf_info.e_type == ET_DYN) ? PIE_LOAD_BASE : 0;

    /* Map ELF segments into guest memory. For x86_64 binaries, the kernel
     * would have already mapped the binary before launching Rosetta as the
     * binfmt_misc interpreter. Rosetta reads /proc/self/maps to discover
     * the binary layout, then either reuses existing mappings or re-maps
     * via MAP_FIXED. Pre-mapping ensures correct /proc/self/maps output
     * and consistent binary data in guest memory. */
    if (elf_map_segments(&elf_info, elf_path,
                         g.host_base, g.guest_size, elf_load_base) < 0) {
        fprintf(stderr, "hl: failed to map ELF segments\n");
        guest_destroy(&g);
        return 1;
    }

    /* Set brk base after the highest loaded segment. */
    uint64_t brk_start = (elf_info.load_max + elf_load_base + 4095) & ~4095ULL;
    if (brk_start < BRK_BASE_DEFAULT)
        brk_start = BRK_BASE_DEFAULT;
    g.brk_base = brk_start;
    g.brk_current = brk_start;

    /* Place stack above brk, 2MB-aligned.  For small binaries the stack
     * stays at the default 128MB position.  For large binaries (e.g.,
     * 200MB pandoc) the stack moves up so it doesn't overlap the binary's
     * address space — rosetta uses MAP_FIXED_NOREPLACE to reserve the
     * binary range and will fail with EEXIST if the stack is in the way. */
    uint64_t stack_top = (brk_start + BLOCK_2MB - 1) & ~(BLOCK_2MB - 1);
    stack_top += STACK_SIZE;                     /* room for 8MB stack */
    if (stack_top < STACK_TOP_DEFAULT)
        stack_top = STACK_TOP_DEFAULT;
    g.stack_top  = stack_top;
    g.stack_base = stack_top - STACK_SIZE;

    /* ---- Step 3b: Load dynamic linker if PT_INTERP present ---- */
    elf_info_t interp_info;
    uint64_t interp_base = 0;
    memset(&interp_info, 0, sizeof(interp_info));

    /* Skip PT_INTERP for x86_64 + rosetta: rosetta handles x86_64
     * dynamic linking internally (loading ld-linux-x86-64.so.2 etc.).
     * We only handle aarch64 interpreters here. */
    if (!need_rosetta && elf_info.interp_path[0] != '\0') {
        /* Resolve interpreter path, applying sysroot if set */
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        if (verbose)
            fprintf(stderr, "hl: loading interpreter: %s\n", interp_resolved);

        if (elf_load(interp_resolved, &interp_info) < 0) {
            fprintf(stderr, "hl: failed to load interpreter: %s\n",
                    interp_resolved);
            guest_destroy(&g);
            return 1;
        }

        /* Load interpreter at dynamic interp_base (computed from guest_size) */
        interp_base = g.interp_base;
        if (elf_map_segments(&interp_info, interp_resolved,
                             g.host_base, g.guest_size, interp_base) < 0) {
            fprintf(stderr, "hl: failed to map interpreter segments\n");
            guest_destroy(&g);
            return 1;
        }

        if (verbose) {
            fprintf(stderr, "hl: interpreter loaded at base=0x%llx, "
                    "entry=0x%llx, %d segments\n",
                    (unsigned long long)interp_base,
                    (unsigned long long)(interp_info.entry + interp_base),
                    interp_info.num_segments);
        }
    }

    /* ---- Step 4: Load shim into guest at SHIM_BASE ---- */
    if (shim_bin_len > BLOCK_2MB) {
        fprintf(stderr, "hl: shim binary too large (%u bytes)\n", shim_bin_len);
        guest_destroy(&g);
        return 1;
    }
    memcpy((uint8_t *)g.host_base + SHIM_BASE, shim_bin, shim_bin_len);

    if (verbose) {
        fprintf(stderr, "hl: shim loaded at offset 0x%llx (%u bytes)\n",
                (unsigned long long)SHIM_BASE, shim_bin_len);
    }

    /* ---- Step 4b: Invalidate I-cache for all loaded code ----
     * ARM64 I-cache and D-cache are not coherent. memcpy above writes
     * code to the D-cache, but the I-cache may hold stale data at these
     * addresses. While fresh mmap'd memory should have cold I-cache,
     * this is defensive — ensures correctness regardless of macOS
     * prefaulting or speculative instruction fetch behavior. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (elf_info.segments[i].flags & PF_X) {
                void *host_addr = (uint8_t *)g.host_base +
                                  elf_info.segments[i].gpa + elf_load_base;
                sys_icache_invalidate(host_addr, elf_info.segments[i].memsz);
            }
        }
    }
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (interp_info.segments[i].flags & PF_X) {
            void *host_addr = (uint8_t *)g.host_base +
                              interp_info.segments[i].gpa + interp_base;
            sys_icache_invalidate(host_addr, interp_info.segments[i].memsz);
        }
    }
    sys_icache_invalidate((uint8_t *)g.host_base + SHIM_BASE, shim_bin_len);

    /* ---- Step 5: Build page tables ---- */
    #define MAX_REGIONS 32
    mem_region_t regions[MAX_REGIONS];
    int nregions = 0;

    /* NOTE: Page table pool is NOT mapped in stage-1 page tables.
     * The MMU hardware walker accesses page tables through stage-2
     * translation (hv_vm_map RWX), so stage-1 mapping is unnecessary.
     * This avoids merging PT pool's RW perms with shim code's RX perms
     * in the same 2MB block, keeping the shim code block as RX. */

    /* Rosetta phase 1: load binary, set up VA aliases/kbuf, append
     * vDSO + rosetta segment regions for the page table builder. */
    /* Resolve ELF path early — needed by rosetta_prepare/finalize */
    char elf_realpath[LINUX_PATH_MAX];
    memset(elf_realpath, 0, sizeof(elf_realpath));
    if (!realpath(elf_path, elf_realpath))
        strncpy(elf_realpath, elf_path, sizeof(elf_realpath) - 1);

    if (need_rosetta) {
        if (rosetta_prepare(&g, elf_realpath, regions, &nregions,
                            MAX_REGIONS, verbose, &rr) < 0) {
            guest_destroy(&g);
            return 1;
        }
    }

    /* Shim code (RX) — sized to just cover the actual binary.
     * IMPORTANT: Apple HVF enforces W^X even with SCTLR.WXN=0.
     * This region must NOT overlap with any RW region in the same
     * 2MB block, or the merged RWX permissions will cause faults. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_BASE,
        .gpa_end   = SHIM_BASE + shim_bin_len,
        .perms     = MEM_PERM_RX
    };

    /* Shim data/stack (RW) */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_DATA_BASE,
        .gpa_end   = SHIM_DATA_BASE + BLOCK_2MB,
        .perms     = MEM_PERM_RW
    };

    /* ELF segments: map each based on its p_flags.
     * For x86_64/rosetta mode, we skip pre-mapping binary segment PTEs.
     * Rosetta does its own mmap(MAP_FIXED) calls to set up the binary's
     * address space, which creates the correct page table entries. If we
     * pre-map here, the initial PROT_NONE reservation would need to
     * invalidate these entries — simpler to let Rosetta manage them.
     * The binary data is already loaded into host memory (elf_map_segments
     * above); PTEs are just not created until Rosetta's MAP_FIXED calls. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (nregions >= MAX_REGIONS) break;
            int perms = MEM_PERM_R;
            if (elf_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
            if (elf_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
            regions[nregions++] = (mem_region_t){
                .gpa_start = elf_info.segments[i].gpa + elf_load_base,
                .gpa_end   = elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                .perms     = perms
            };
        }
    }

    /* Interpreter segments (if dynamic linking) */
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (interp_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (interp_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        regions[nregions++] = (mem_region_t){
            .gpa_start = interp_info.segments[i].gpa + interp_base,
            .gpa_end   = interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
            .perms     = perms
        };
    }

    /* brk region (RW). Pre-mapped up to MMAP_RX_BASE; brk can grow
     * beyond via dynamic page table extension in sys_brk. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.brk_base,
        .gpa_end   = MMAP_RX_BASE,
        .perms     = MEM_PERM_RW
    };

    /* Stack (RW) — position is dynamic (above brk) */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.stack_base,
        .gpa_end   = g.stack_top,
        .perms     = MEM_PERM_RW
    };

    /* mmap RX region (separate 2MB blocks for PROT_EXEC allocations).
     * Apple HVF enforces W^X on page table entries: a 2MB block can't be
     * both writable and executable. Shared library text (PROT_EXEC) goes
     * here, separate from RW data in the main mmap region. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_RX_BASE,
        .gpa_end   = MMAP_RX_INITIAL_END,
        .perms     = MEM_PERM_RX
    };
    g.mmap_rx_end = MMAP_RX_INITIAL_END;

    /* mmap RW region (pre-mapped up to MMAP_INITIAL_END at 8GB+256MB).
     * Starts at 8GB to match real Linux kernel address space layout where
     * mmap regions are well above the program text/data/brk. Programs
     * may assume mmap returns high addresses (e.g. for pointer tagging
     * or address-space partitioning). Additional pages beyond
     * MMAP_INITIAL_END are mapped dynamically by
     * guest_extend_page_tables(). */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_BASE,
        .gpa_end   = MMAP_INITIAL_END,
        .perms     = MEM_PERM_RW
    };
    g.mmap_end = MMAP_INITIAL_END;

    if (0) {
too_many_regions:
        fprintf(stderr, "hl: too many memory regions (%d >= %d)\n",
                nregions, MAX_REGIONS);
        guest_destroy(&g);
        return 1;
    }

    uint64_t ttbr0 = guest_build_page_tables(&g, regions, nregions);
    if (!ttbr0) {
        fprintf(stderr, "hl: failed to build page tables\n");
        guest_destroy(&g);
        return 1;
    }

    /* ---- Step 5b: Record semantic regions for /proc/self/maps ---- */
    guest_region_add(&g, SHIM_BASE, SHIM_BASE + shim_bin_len,
                     LINUX_PROT_READ | LINUX_PROT_EXEC, LINUX_MAP_PRIVATE,
                     0, "[shim]");
    guest_region_add(&g, SHIM_DATA_BASE, SHIM_DATA_BASE + BLOCK_2MB,
                     LINUX_PROT_READ | LINUX_PROT_WRITE, LINUX_MAP_PRIVATE,
                     0, "[shim-data]");

    /* In rosetta mode, do NOT register the x86_64 binary segments in
     * regions[]. Rosetta expects to reserve the binary's address range
     * via MAP_FIXED_NOREPLACE and then map the binary itself. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (elf_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (elf_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g, elf_info.segments[i].gpa + elf_load_base,
                             elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                             prot, LINUX_MAP_PRIVATE,
                             elf_info.segments[i].offset, elf_realpath);
        }
    }

    /* Interpreter semantic regions (if dynamic linking) */
    if (interp_info.num_segments > 0) {
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        for (int i = 0; i < interp_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (interp_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (interp_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g,
                             interp_info.segments[i].gpa + interp_base,
                             interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
                             prot, LINUX_MAP_PRIVATE,
                             interp_info.segments[i].offset, interp_resolved);
        }
    }

    /* Heap starts at brk_base (initially empty, grows via sys_brk) */
    if (g.brk_base < g.brk_current) {
        guest_region_add(&g, g.brk_base, g.brk_current,
                         LINUX_PROT_READ | LINUX_PROT_WRITE,
                         LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                         0, "[heap]");
    }

    /* Stack guard page: PROT_NONE at bottom to catch overflow */
    guest_invalidate_ptes(&g, g.stack_base, g.stack_base + STACK_GUARD_SIZE);
    guest_region_add(&g, g.stack_base, g.stack_base + STACK_GUARD_SIZE,
                     LINUX_PROT_NONE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack-guard]");
    guest_region_add(&g, g.stack_base + STACK_GUARD_SIZE, g.stack_top,
                     LINUX_PROT_READ | LINUX_PROT_WRITE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack]");

    /* Null guard page: invalidate page 0 so NULL dereferences produce
     * a translation fault (EC=0x20 → SIGSEGV) instead of executing
     * zero-initialized memory (UDF #0 → EC=0x00 → SIGILL). The shim
     * starts at SHIM_BASE=0x100000 but its 2MB L2 block covers 0x0–
     * 0x1FFFFF with RX permissions. Splitting into L3 pages and
     * invalidating page 0 matches Linux kernel behavior. */
    guest_invalidate_ptes(&g, 0, 0x1000);

    if (verbose) {
        fprintf(stderr, "hl: TTBR0=0x%llx, IPA base=0x%llx\n",
                (unsigned long long)ttbr0, (unsigned long long)g.ipa_base);

        /* Dump page table structure */
        uint64_t l0_off = ttbr0 - g.ipa_base;
        uint64_t *l0 = (uint64_t *)((uint8_t *)g.host_base + l0_off);
        unsigned l0i = (unsigned)(g.ipa_base / (512ULL * 1024 * 1024 * 1024));
        fprintf(stderr, "hl: L0[%u]=0x%llx\n", l0i,
                (unsigned long long)l0[l0i]);

        uint64_t l1_ipa = l0[l0i] & 0xFFFFFFFFF000ULL;
        uint64_t *l1 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l1_ipa - g.ipa_base));
        unsigned l1i = (unsigned)((g.ipa_base % (512ULL * 1024 * 1024 * 1024))
                                  / (1024ULL * 1024 * 1024));
        fprintf(stderr, "hl: L1[%u]=0x%llx\n", l1i,
                (unsigned long long)l1[l1i]);

        uint64_t l2_ipa = l1[l1i] & 0xFFFFFFFFF000ULL;
        uint64_t *l2 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l2_ipa - g.ipa_base));
        for (int i = 0; i < 16; i++) {
            if (l2[i])
                fprintf(stderr, "hl: L2[%d]=0x%llx\n", i,
                        (unsigned long long)l2[i]);
        }
    }

    /* ---- Step 6: Build Linux initial stack ---- */
    syscall_init();
    proc_init();

    /* Record the absolute path of the hl binary itself so that
     * sub-processes (rosettad AOT translation) can invoke it. */
    {
        char self_path[LINUX_PATH_MAX];
        uint32_t path_len = sizeof(self_path);
        if (_NSGetExecutablePath(self_path, &path_len) == 0)
            proc_set_hl_path(self_path);
    }

    proc_set_shim(shim_bin, shim_bin_len);
    if (!need_rosetta)
        proc_set_elf_path(elf_path);
    if (sysroot)
        proc_set_sysroot(sysroot);
    extern char **environ;
    uint64_t sp;
    uint64_t entry_point;

    /* ---- Step 7: Create vCPU and configure registers ---- */
    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    HV_CHECK(hv_vcpu_create(&vcpu, &vexit, NULL));
    g.vcpu = vcpu;
    g.exit = vexit;

    if (need_rosetta) {
        /* Rosetta phase 2: kbuf dual-mapping, vDSO, fd 3, argv, proc state.
         * Needs vcpu handle for TCR_EL1/TTBR1_EL1 sysreg writes.
         * Pass elf_path (not elf_realpath) so multi-call binaries (e.g.
         * symlinks echo→coreutils) see the correct argv[0]. open() and
         * rosettad both follow symlinks, so the original path works. */
        int rosetta_argc;
        const char **rosetta_argv;
        uint64_t vdso_addr;
        if (rosetta_finalize(&g, vcpu, elf_path,
                             guest_argc, guest_argv, &rr, verbose,
                             &rosetta_argc, &rosetta_argv, &vdso_addr) < 0) {
            hv_vcpu_destroy(vcpu);
            guest_destroy(&g);
            return 1;
        }

        /* Stack auxv describes rosetta as the main binary (binfmt_misc
         * semantics: AT_PHDR/PHENT/PHNUM/ENTRY all refer to rosetta). */
        sp = build_linux_stack(&g, g.stack_top,
                               rosetta_argc, rosetta_argv,
                               (const char **)environ, &rr.rosetta_info,
                               0 /* rosetta is ET_EXEC at link addr */,
                               0 /* no dynamic linker for rosetta */,
                               vdso_addr,
                               3 /* AT_EXECFD: binary pre-opened at fd 3 */);
        free((void *)rosetta_argv);
        if (sp == 0) {
            fprintf(stderr, "hl: failed to build initial stack\n");
            hv_vcpu_destroy(vcpu);
            guest_destroy(&g);
            return 1;
        }
        entry_point = rr.entry_point;
    } else {
        /* Normal aarch64 mode */
        proc_set_cmdline(guest_argc, guest_argv);

        /* Build vDSO for the signal restorer fallback (sa_restorer == 0).
         * musl/glibc always set sa_restorer, but raw rt_sigaction users
         * or other libc implementations may rely on the kernel-provided
         * vDSO trampoline. Building it unconditionally is safe (1 page). */
        uint64_t native_vdso = vdso_build(&g);

        sp = build_linux_stack(&g, g.stack_top,
                               guest_argc, guest_argv,
                               (const char **)environ, &elf_info,
                               elf_load_base, interp_base,
                               native_vdso,
                               -1 /* no AT_EXECFD */);
        if (sp == 0) {
            fprintf(stderr, "hl: failed to build initial stack\n");
            hv_vcpu_destroy(vcpu);
            guest_destroy(&g);
            return 1;
        }

        /* Entry point: interpreter entry if dynamic, ELF entry if static. */
        entry_point = (interp_base != 0)
            ? (interp_info.entry + interp_base)
            : (elf_info.entry + elf_load_base);
    }

    if (verbose)
        fprintf(stderr, "hl: SP=0x%llx, entry=0x%llx%s\n",
                (unsigned long long)sp,
                (unsigned long long)entry_point,
                need_rosetta ? " (via rosetta)" :
                interp_base ? " (via interpreter)" : "");

    /* All guest-visible addresses are IPA-based: GUEST_IPA_BASE + offset */
    uint64_t shim_ipa  = guest_ipa(&g, SHIM_BASE);
    uint64_t entry_ipa = guest_ipa(&g, entry_point);
    uint64_t sp_ipa    = guest_ipa(&g, sp);
    uint64_t el1_sp    = guest_ipa(&g, SHIM_DATA_BASE + BLOCK_2MB);

    /* Register main thread in the thread table (before entering run loop) */
    thread_register_main(vcpu, vexit, proc_get_pid(), el1_sp);

    /* -- System registers (set from host; MMU enable deferred to HVC #4) -- */

    /* VBAR_EL1: vector table at shim_base + 0x800 (.align 11 offset) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_VBAR_EL1,
                                 shim_ipa + 0x800));

    /* MAIR_EL1: Attr0=Device-nGnRnE (0x00), Attr1=Normal WB (0xFF) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_MAIR_EL1, 0xFF00));

    /* TCR_EL1: 4KB granule, 48-bit VA.
     * When kernel VA buffer is active (rosetta mode), enable TTBR1 walks
     * (EPD1=0) so kernel-space addresses are translated via TTBR1. */
    uint64_t tcr_value = g.kbuf_base ? TCR_EL1_VALUE_KBUF : TCR_EL1_VALUE;
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TCR_EL1, tcr_value));

    /* TTBR0_EL1: page table base (IPA from guest_build_page_tables) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR0_EL1, ttbr0));

    /* TTBR1_EL1: kernel VA page tables (rosetta mode) or unused */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR1_EL1,
                                  g.ttbr1 ? g.ttbr1 : 0));

    /* CPACR_EL1: enable FP/SIMD at EL0 and EL1 (FPEN=0b11) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_CPACR_EL1, 3ULL << 20));

    /* ELR_EL1: EL0 entry point (shim will ERET to this address) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_ELR_EL1, entry_ipa));

    /* SPSR_EL1: EL0t, AArch64, all interrupts masked on entry */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SPSR_EL1, 0x0));

    /* SP_EL0: initial stack pointer for EL0 */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL0, sp_ipa));

    /* SP_EL1: EL1 stack for exception handlers (top of shim data region) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL1, el1_sp));

    /* SCTLR_EL1: read default, then enable MMU + caches */
    uint64_t sctlr;
    HV_CHECK(hv_vcpu_get_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, &sctlr));
    if (verbose)
        fprintf(stderr, "hl: SCTLR_EL1 default=0x%llx\n",
                (unsigned long long)sctlr);

    /* Build a proper SCTLR with RES1 bits + caches, but WITHOUT MMU enable.
     * Apple's HVF requires the MMU to be enabled DURING vCPU execution
     * (via HVC #4 from the shim), not before hv_vcpu_run. Setting SCTLR.M=1
     * via hv_vcpu_set_sys_reg before start causes permission faults.
     * The shim will HVC #4 to enable M after TLBI/DSB/ISB. */
    sctlr = SCTLR_RES1 | SCTLR_C | SCTLR_I
          | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;  /* No SCTLR_M here */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, sctlr));

    /* -- General purpose registers -- */

    /* PC = shim entry (TLBI + zero regs + ERET) */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_PC, shim_ipa));

    /* CPSR = EL1h (0x3c5) — shim runs at EL1 */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_CPSR, 0x3c5));

    /* Zero all general purpose registers */
    for (int i = 0; i < 31; i++) {
        HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0 + i, 0));
    }

    /* Pass the full SCTLR value (WITH M=1) in X0 for the shim to
     * enable the MMU during execution via HVC #4. */
    uint64_t sctlr_with_mmu = SCTLR_RES1 | SCTLR_M | SCTLR_C | SCTLR_I
                            | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0, sctlr_with_mmu));

    if (verbose) {
        fprintf(stderr, "hl: vCPU configured: PC=0x%llx SCTLR=0x%llx "
                "VBAR=0x%llx TTBR0=0x%llx TCR=0x%llx\n",
                (unsigned long long)shim_ipa,
                (unsigned long long)sctlr,
                (unsigned long long)(shim_ipa + 0x800),
                (unsigned long long)ttbr0,
                (unsigned long long)tcr_value);
        fprintf(stderr, "hl: ELR_EL1=0x%llx SP_EL0=0x%llx SP_EL1=0x%llx\n",
                (unsigned long long)entry_ipa,
                (unsigned long long)sp_ipa,
                (unsigned long long)el1_sp);
    }

    /* ---- Step 7b: Initialize GDB stub (if requested) ---- */
    if (gdb_port > 0 && !need_rosetta) {
        if (gdb_stub_init(gdb_port, &g) < 0) {
            fprintf(stderr, "hl: failed to initialize GDB stub\n");
            hv_vcpu_destroy(vcpu);
            guest_destroy(&g);
            return 1;
        }
        /* Program debug registers on the initial vCPU */
        gdb_stub_sync_debug_regs(vcpu);

        if (gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    } else if (gdb_port > 0 && need_rosetta) {
        fprintf(stderr, "hl: --gdb is not supported for x86_64/rosetta "
                "binaries (JIT makes source-level debugging meaningless)\n");
    }

    /* ---- Step 8: vCPU execution loop ---- */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec);

    /* ---- Cleanup ---- */
    gdb_stub_shutdown();
    guest_destroy(&g);

    return exit_code;
}
