/* hl.c — Run aarch64-linux and x86_64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2025 Moritz Angermann <moritz@zw3rk.com>, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *   - x86_64-linux support via Apple's Rosetta Linux translator, which
 *     JIT-translates x86_64 instructions to ARM64 syscalls transparently.
 *
 * Usage: hl [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */
#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <libkern/OSCacheControl.h>
#include <mach-o/dyld.h>

#include "guest.h"
#include "elf.h"
#include "syscall.h"
#include "syscall_internal.h"  /* LINUX_PATH_MAX (for elf_path realpath) */
#include "syscall_proc.h"
#include "hv_util.h"
#include "fork_ipc.h"
#include "stack.h"
#include "vdso.h"
#include "thread.h"

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* Build-time version string (generated by make into _build/version.h) */
#include "version.h"

/* ---------- TCR_EL1 ---------- */

/* TCR_EL1 for 4KB granule, 48-bit VA:
 *   T0SZ  = 16  (48-bit TTBR0 VA space)
 *   IRGN0 = WB RA WA, ORGN0 = WB RA WA, SH0 = Inner Shareable
 *   TG0   = 4KB
 *   T1SZ  = 16  (48-bit TTBR1 VA space)
 *   EPD1  = 1   (DISABLE TTBR1 walks — cleared for rosetta mode)
 *   IRGN1 = WB RA WA, ORGN1 = WB RA WA, SH1 = Inner Shareable
 *   TG1   = 4KB (encoding 0b10)
 *   IPS   = 48-bit PA (0b101)
 *   TBI0  = 1   (Top Byte Ignore for TTBR0: bits [63:56] of VA are ignored
 *                during translation. Enables pointer tagging for user VA.)
 *   TBI1  = 1   (Top Byte Ignore for TTBR1: bits [63:56] of VA are ignored
 *                during translation for kernel VA. Required for rosetta:
 *                JIT code stores metadata tags in the top byte of kernel VA
 *                pointers, e.g. 0x7FFFFFFFF7DF... → effective 0xFFFFF7DF...)
 *
 * Bit layout:
 *   [5:0]   T0SZ   = 0x10
 *   [7]     EPD0   = 0
 *   [9:8]   IRGN0  = 0b01
 *   [11:10] ORGN0  = 0b01
 *   [13:12] SH0    = 0b11
 *   [15:14] TG0    = 0b00
 *   [21:16] T1SZ   = 0x10
 *   [22]    A1     = 0
 *   [23]    EPD1   = 1 (or 0 for rosetta)
 *   [25:24] IRGN1  = 0b01
 *   [27:26] ORGN1  = 0b01
 *   [29:28] SH1    = 0b11
 *   [31:30] TG1    = 0b10
 *   [34:32] IPS    = 0b101
 *   [37]    TBI0   = 1
 *   [38]    TBI1   = 1 (rosetta mode only)
 */
#define TCR_EL1_VALUE       0x25B5903510ULL  /* EPD1=1: TTBR1 walks disabled */
#define TCR_EL1_VALUE_KBUF  0x65B5103510ULL  /* EPD1=0, TBI1=1: TTBR1 + TBI */

/* ---------- Main ---------- */

int main(int argc, const char **argv) {
    int verbose = 0;
    int timeout_sec = 10;  /* Default: 10 second timeout */
    int fork_child_fd = -1; /* IPC fd for --fork-child mode */
    const char *sysroot = NULL; /* Sysroot for dynamic linker resolution */
    int arg_start = 1;

    /* Handle --version / --help before option parsing */
    if (argc > 1) {
        if (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-V") == 0) {
            printf("hl %s\n", HL_VERSION);
            return 0;
        }
        if (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
            /* Locate man page relative to binary.  execlp replaces the
             * process, so we must check access() before each attempt —
             * once man(1) runs, there is no fallback. */
            char man_path[4096];
            const char *slash = strrchr(argv[0], '/');
            if (slash) {
                int dirlen = (int)(slash - argv[0]);
                /* Installed: <bindir>/../share/man/man1/hl.1 */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../share/man/man1/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Source tree: <bindir>/../hl.1  (binary in _build/) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Distribution zip: <bindir>/hl.1  (binary and man page side by side) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
            }
            /* System man path (last resort — replaces process) */
            execlp("man", "man", "1", "hl", (char *)NULL);
            /* man not available at all */
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Parse hl options */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (strcmp(argv[arg_start], "--verbose") == 0 ||
            strcmp(argv[arg_start], "-v") == 0) {
            verbose = 1;
            arg_start++;
        } else if ((strcmp(argv[arg_start], "--timeout") == 0 ||
                    strcmp(argv[arg_start], "-t") == 0) &&
                   arg_start + 1 < argc) {
            timeout_sec = atoi(argv[arg_start + 1]);
            if (timeout_sec <= 0) timeout_sec = 10;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--fork-child") == 0 &&
                   arg_start + 1 < argc) {
            fork_child_fd = atoi(argv[arg_start + 1]);
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--sysroot") == 0 &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--") == 0) {
            arg_start++;
            break;
        } else {
            fprintf(stderr, "hl: unknown option: %s\n", argv[arg_start]);
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Fork-child mode: receive VM state over IPC and run */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, verbose, timeout_sec);

    if (arg_start >= argc) {
        fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                "[--sysroot PATH] <elf-path> [args...]\n");
        return 1;
    }

    const char *elf_path = argv[arg_start];
    int guest_argc = argc - arg_start;
    const char **guest_argv = &argv[arg_start];

    /* ---- Step 1: Load and parse ELF ---- */
    elf_info_t elf_info;
    if (elf_load(elf_path, &elf_info) < 0) {
        fprintf(stderr, "hl: failed to load ELF: %s\n", elf_path);
        return 1;
    }

    if (verbose) {
        fprintf(stderr, "hl: ELF entry=0x%llx, %d segments, "
                "load range [0x%llx, 0x%llx), machine=%s\n",
                (unsigned long long)elf_info.entry,
                elf_info.num_segments,
                (unsigned long long)elf_info.load_min,
                (unsigned long long)elf_info.load_max,
                elf_info.e_machine == EM_AARCH64 ? "aarch64" : "x86_64");
    }

    /* ---- Step 1b: Detect x86_64 and prepare rosetta translator ---- */
    int need_rosetta = (elf_info.e_machine == EM_X86_64);
    elf_info_t rosetta_info;
    memset(&rosetta_info, 0, sizeof(rosetta_info));

    if (need_rosetta) {
        if (access(ROSETTA_PATH, X_OK) != 0) {
            fprintf(stderr, "hl: x86_64 binary requires Rosetta Linux translator\n"
                    "    not found at: %s\n"
                    "    install Rosetta via: softwareupdate --install-rosetta\n",
                    ROSETTA_PATH);
            return 1;
        }
        if (elf_load(ROSETTA_PATH, &rosetta_info) < 0) {
            fprintf(stderr, "hl: failed to load rosetta: %s\n", ROSETTA_PATH);
            return 1;
        }
        if (verbose)
            fprintf(stderr, "hl: x86_64 detected, rosetta entry=0x%llx, "
                    "load range [0x%llx, 0x%llx)\n",
                    (unsigned long long)rosetta_info.entry,
                    (unsigned long long)rosetta_info.load_min,
                    (unsigned long long)rosetta_info.load_max);
    }

    /* ---- Step 2: Initialize guest memory and VM ---- */
    /* Auto-detect IPA size (36/40-bit). Rosetta's high VA (128TB) is
     * handled via page tables mapping to a low GPA within the primary
     * buffer — no high IPA needed. */
    guest_t g;
    if (guest_init(&g, 0, 0) < 0) {
        fprintf(stderr, "hl: failed to initialize guest\n");
        return 1;
    }
    g.is_rosetta = need_rosetta;

    /* ---- Step 2b: Place rosetta in the primary buffer ---- */
    /* Rosetta's ELF link address is at 128TB (VA 0x800000000000), but we
     * don't need 48-bit IPA — only 48-bit VA. We place rosetta's segments
     * in the primary buffer at a low GPA and use the page tables to map
     * VA 0x800000000000 → low GPA. The MMU translates VA→IPA; HVF
     * translates IPA→host. Both are independent.
     *
     * Layout: rosetta goes just below interp_base in the primary buffer.
     * This avoids conflicting with mmap regions or the dynamic linker. */
    uint64_t rosetta_guest_base = 0;  /* GPA offset for rosetta in primary buf */
    uint64_t rosetta_va_base = 0;     /* VA start (rosetta's link address) */
    uint64_t rosetta_size = 0;

    if (need_rosetta) {
        /* Compute 2MB-aligned rosetta segment span */
        rosetta_va_base = rosetta_info.load_min & ~(BLOCK_2MB - 1);
        uint64_t rosetta_va_end = (rosetta_info.load_max + BLOCK_2MB - 1)
                                   & ~(BLOCK_2MB - 1);
        rosetta_size = rosetta_va_end - rosetta_va_base;

        /* Place just below interp_base, 2MB-aligned */
        rosetta_guest_base = (g.interp_base - rosetta_size) & ~(BLOCK_2MB - 1);

        /* Load rosetta segments into the primary buffer. The load_base
         * offsets the high VAs down to the guest base offset:
         * e.g., 0x800000000000 → rosetta_guest_base. */
        uint64_t rosetta_load_base = rosetta_guest_base - rosetta_va_base;
        if (elf_map_segments(&rosetta_info, ROSETTA_PATH,
                             g.host_base, g.guest_size,
                             rosetta_load_base) < 0) {
            fprintf(stderr, "hl: failed to map rosetta segments\n");
            guest_destroy(&g);
            return 1;
        }

        /* Register VA alias so syscall handlers can resolve rosetta's
         * high virtual addresses (0x800000000000+) to host pointers.
         * The CPU's page tables handle VA→IPA for instruction fetch, but
         * guest_ptr/read/write need this alias for memory access. */
        if (guest_add_va_alias(&g, rosetta_va_base,
                               rosetta_guest_base, rosetta_size) < 0) {
            fprintf(stderr, "hl: failed to register rosetta VA alias\n");
            guest_destroy(&g);
            return 1;
        }

        if (verbose)
            fprintf(stderr, "hl: rosetta loaded at GPA 0x%llx (VA 0x%llx), "
                    "%lluMB\n",
                    (unsigned long long)rosetta_guest_base,
                    (unsigned long long)rosetta_va_base,
                    (unsigned long long)(rosetta_size / (1024 * 1024)));

        /* Initialize kbuf (kernel VA backing store) for rosetta.
         * Rosetta mmaps internal data (ELF headers, JIT cache, thread
         * stacks) at kernel VA addresses (0xFFFFFFFFF0000000+). The
         * backing memory lives in the primary buffer at kbuf_gpa.
         *
         * IMPORTANT: sys_mmap returns USER VA aliases (KBUF_USER_VA+off)
         * instead of kernel VA for these allocations. Rosetta's tagged
         * pointer system (TaggedPointer.h) asserts bits 63:48 == 0,
         * which kernel VA (0xFFFF...) violates. User VA aliases pass
         * the assertion while pointing to the same physical backing. */
        uint64_t kbuf_gpa = (rosetta_guest_base + rosetta_size + BLOCK_2MB - 1)
                            & ~(BLOCK_2MB - 1);
        if (guest_init_kbuf(&g, kbuf_gpa) < 0) {
            fprintf(stderr, "hl: failed to initialize kbuf\n");
            guest_destroy(&g);
            return 1;
        }
        /* Register user VA alias for kbuf so syscall handlers (guest_ptr,
         * guest_read, guest_write) can resolve the user VA addresses we
         * return from kernel VA mmaps. */
        guest_add_va_alias(&g, KBUF_USER_VA, kbuf_gpa, KBUF_SIZE);

        /* Rosetta's init populates its own signal handler table:
         *   save_old_handler(5)  → queries rt_sigaction(5,NULL,&old,8)
         *                          stores old handler (SIG_DFL=0) in BSS[0x488+5*32]
         *                          sets BSS[0x478] |= (1<<5)
         *   save_old_handler(11) → same for SIGSEGV
         *   rt_sigaction(11, handler=0x96490) → installs SIGSEGV
         *   rt_sigaction(5,  handler=0x96490) → installs SIGTRAP
         *
         * The BSS[0x488+sig*32] entry stores the OLD (pre-rosetta) handler,
         * NOT rosetta's own handler. In the signal dispatch at 0x2e898:
         *   old_handler < 2 (SIG_DFL/SIG_IGN) → rosetta's JIT handles it
         *   old_handler >= 2 → forward to pre-existing handler
         * So the correct BSS state after init is {0,0,0,0} (SIG_DFL). */
    }

    /* ---- Step 3: Load ELF segments into guest memory ---- */
    /* PIE executables (ET_DYN) have virtual addresses starting near 0,
     * which would overlap with the page table pool and shim. Load them
     * at PIE_LOAD_BASE (0x400000) instead. ET_EXEC binaries already
     * have absolute addresses (typically 0x400000+), so use base 0. */
    uint64_t elf_load_base = (elf_info.e_type == ET_DYN) ? PIE_LOAD_BASE : 0;

    /* Map ELF segments into guest memory. For x86_64 binaries, the kernel
     * would have already mapped the binary before launching Rosetta as the
     * binfmt_misc interpreter. Rosetta reads /proc/self/maps to discover
     * the binary layout, then either reuses existing mappings or re-maps
     * via MAP_FIXED. Pre-mapping ensures correct /proc/self/maps output
     * and consistent binary data in guest memory. */
    if (elf_map_segments(&elf_info, elf_path,
                         g.host_base, g.guest_size, elf_load_base) < 0) {
        fprintf(stderr, "hl: failed to map ELF segments\n");
        guest_destroy(&g);
        return 1;
    }

    /* Set brk base after the highest loaded segment. */
    uint64_t brk_start = (elf_info.load_max + elf_load_base + 4095) & ~4095ULL;
    if (brk_start < BRK_BASE_DEFAULT)
        brk_start = BRK_BASE_DEFAULT;
    g.brk_base = brk_start;
    g.brk_current = brk_start;

    /* ---- Step 3b: Load dynamic linker if PT_INTERP present ---- */
    elf_info_t interp_info;
    uint64_t interp_base = 0;
    memset(&interp_info, 0, sizeof(interp_info));

    /* Skip PT_INTERP for x86_64 + rosetta: rosetta handles x86_64
     * dynamic linking internally (loading ld-linux-x86-64.so.2 etc.).
     * We only handle aarch64 interpreters here. */
    if (!need_rosetta && elf_info.interp_path[0] != '\0') {
        /* Resolve interpreter path, applying sysroot if set */
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        if (verbose)
            fprintf(stderr, "hl: loading interpreter: %s\n", interp_resolved);

        if (elf_load(interp_resolved, &interp_info) < 0) {
            fprintf(stderr, "hl: failed to load interpreter: %s\n",
                    interp_resolved);
            guest_destroy(&g);
            return 1;
        }

        /* Load interpreter at dynamic interp_base (computed from guest_size) */
        interp_base = g.interp_base;
        if (elf_map_segments(&interp_info, interp_resolved,
                             g.host_base, g.guest_size, interp_base) < 0) {
            fprintf(stderr, "hl: failed to map interpreter segments\n");
            guest_destroy(&g);
            return 1;
        }

        if (verbose) {
            fprintf(stderr, "hl: interpreter loaded at base=0x%llx, "
                    "entry=0x%llx, %d segments\n",
                    (unsigned long long)interp_base,
                    (unsigned long long)(interp_info.entry + interp_base),
                    interp_info.num_segments);
        }
    }

    /* ---- Step 4: Load shim into guest at SHIM_BASE ---- */
    if (shim_bin_len > BLOCK_2MB) {
        fprintf(stderr, "hl: shim binary too large (%u bytes)\n", shim_bin_len);
        guest_destroy(&g);
        return 1;
    }
    memcpy((uint8_t *)g.host_base + SHIM_BASE, shim_bin, shim_bin_len);

    if (verbose) {
        fprintf(stderr, "hl: shim loaded at offset 0x%llx (%u bytes)\n",
                (unsigned long long)SHIM_BASE, shim_bin_len);
    }

    /* ---- Step 4b: Invalidate I-cache for all loaded code ----
     * ARM64 I-cache and D-cache are not coherent. memcpy above writes
     * code to the D-cache, but the I-cache may hold stale data at these
     * addresses. While fresh mmap'd memory should have cold I-cache,
     * this is defensive — ensures correctness regardless of macOS
     * prefaulting or speculative instruction fetch behavior. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (elf_info.segments[i].flags & PF_X) {
                void *host_addr = (uint8_t *)g.host_base +
                                  elf_info.segments[i].gpa + elf_load_base;
                sys_icache_invalidate(host_addr, elf_info.segments[i].memsz);
            }
        }
    }
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (interp_info.segments[i].flags & PF_X) {
            void *host_addr = (uint8_t *)g.host_base +
                              interp_info.segments[i].gpa + interp_base;
            sys_icache_invalidate(host_addr, interp_info.segments[i].memsz);
        }
    }
    sys_icache_invalidate((uint8_t *)g.host_base + SHIM_BASE, shim_bin_len);
    /* Rosetta segments: in primary buffer at rosetta_guest_base offset */
    for (int i = 0; i < rosetta_info.num_segments; i++) {
        if (rosetta_info.segments[i].flags & PF_X) {
            uint64_t seg_gpa = rosetta_guest_base +
                               (rosetta_info.segments[i].gpa - rosetta_va_base);
            void *host_addr = (uint8_t *)g.host_base + seg_gpa;
            sys_icache_invalidate(host_addr, rosetta_info.segments[i].memsz);
        }
    }

    /* ---- Step 5: Build page tables ---- */
    #define MAX_REGIONS 32
    mem_region_t regions[MAX_REGIONS];
    int nregions = 0;

    /* NOTE: Page table pool is NOT mapped in stage-1 page tables.
     * The MMU hardware walker accesses page tables through stage-2
     * translation (hv_vm_map RWX), so stage-1 mapping is unnecessary.
     * This avoids merging PT pool's RW perms with shim code's RX perms
     * in the same 2MB block, keeping the shim code block as RX. */

    /* vDSO page (RX): mapped at VDSO_BASE (0xF000) if rosetta needs it.
     * Shares the first 2MB block with the shim — both are RX so
     * permissions merge correctly. Only emitted for rosetta mode since
     * aarch64 binaries don't need a vDSO. */
    if (need_rosetta) {
        regions[nregions++] = (mem_region_t){
            .gpa_start = VDSO_BASE,
            .gpa_end   = VDSO_BASE + VDSO_SIZE,
            .perms     = MEM_PERM_RX
        };
    }

    /* Shim code (RX) — sized to just cover the actual binary.
     * IMPORTANT: Apple HVF enforces W^X even with SCTLR.WXN=0.
     * This region must NOT overlap with any RW region in the same
     * 2MB block, or the merged RWX permissions will cause faults. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_BASE,
        .gpa_end   = SHIM_BASE + shim_bin_len,
        .perms     = MEM_PERM_RX
    };

    /* Shim data/stack (RW) */
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_DATA_BASE,
        .gpa_end   = SHIM_DATA_BASE + BLOCK_2MB,
        .perms     = MEM_PERM_RW
    };

    /* ELF segments: map each based on its p_flags.
     * For x86_64/rosetta mode, we skip pre-mapping binary segment PTEs.
     * Rosetta does its own mmap(MAP_FIXED) calls to set up the binary's
     * address space, which creates the correct page table entries. If we
     * pre-map here, the initial PROT_NONE reservation would need to
     * invalidate these entries — simpler to let Rosetta manage them.
     * The binary data is already loaded into host memory (elf_map_segments
     * above); PTEs are just not created until Rosetta's MAP_FIXED calls. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (nregions >= MAX_REGIONS) break;
            int perms = MEM_PERM_R;
            if (elf_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
            if (elf_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
            regions[nregions++] = (mem_region_t){
                .gpa_start = elf_info.segments[i].gpa + elf_load_base,
                .gpa_end   = elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                .perms     = perms
            };
        }
    }

    /* Interpreter segments (if dynamic linking) */
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (interp_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (interp_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        regions[nregions++] = (mem_region_t){
            .gpa_start = interp_info.segments[i].gpa + interp_base,
            .gpa_end   = interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
            .perms     = perms
        };
    }

    /* brk region (RW). Pre-mapped up to MMAP_RX_BASE; brk can grow
     * beyond via dynamic page table extension in sys_brk. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.brk_base,
        .gpa_end   = MMAP_RX_BASE,
        .perms     = MEM_PERM_RW
    };

    /* Stack (RW) */
    regions[nregions++] = (mem_region_t){
        .gpa_start = STACK_BASE,
        .gpa_end   = STACK_TOP,
        .perms     = MEM_PERM_RW
    };

    /* mmap RX region (separate 2MB blocks for PROT_EXEC allocations).
     * Apple HVF enforces W^X on page table entries: a 2MB block can't be
     * both writable and executable. Shared library text (PROT_EXEC) goes
     * here, separate from RW data in the main mmap region. */
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_RX_BASE,
        .gpa_end   = MMAP_RX_INITIAL_END,
        .perms     = MEM_PERM_RX
    };
    g.mmap_rx_end = MMAP_RX_INITIAL_END;

    /* mmap RW region (pre-mapped up to MMAP_INITIAL_END at 8GB+256MB).
     * Starts at 8GB to match real Linux kernel address space layout where
     * mmap regions are well above the program text/data/brk. Programs
     * may assume mmap returns high addresses (e.g. for pointer tagging
     * or address-space partitioning). Additional pages beyond
     * MMAP_INITIAL_END are mapped dynamically by
     * guest_extend_page_tables(). */
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_BASE,
        .gpa_end   = MMAP_INITIAL_END,
        .perms     = MEM_PERM_RW
    };
    g.mmap_end = MMAP_INITIAL_END;

    /* Rosetta segments: non-identity mapping. VA is at 128TB (rosetta's
     * link address), but the data lives in the primary buffer at
     * rosetta_guest_base. The page table builder uses va_base for L0/L1/L2
     * index computation and gpa_start for block descriptor output. */
    for (int i = 0; i < rosetta_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (rosetta_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (rosetta_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        /* GPA = where data physically lives in primary buffer */
        uint64_t seg_gpa = rosetta_guest_base +
                           (rosetta_info.segments[i].gpa - rosetta_va_base);
        regions[nregions++] = (mem_region_t){
            .gpa_start = seg_gpa,
            .gpa_end   = seg_gpa + rosetta_info.segments[i].memsz,
            .va_base   = rosetta_info.segments[i].gpa,  /* High VA */
            .perms     = perms
        };
    }

    uint64_t ttbr0 = guest_build_page_tables(&g, regions, nregions);
    if (!ttbr0) {
        fprintf(stderr, "hl: failed to build page tables\n");
        guest_destroy(&g);
        return 1;
    }

    /* If kbuf is active, create dual-mapping: the kbuf's TTBR1 pages
     * (kernel VA 0xFFFFFFFFF0000000) are also accessible at user VA
     * (0x0000FFFFF0000000) via TTBR0 page table entries pointing to the
     * same GPA range. This supports rosetta's tagged pointer system:
     * BFI inserts a tag into bits 63:48, and get_pointer extracts
     * bits 47:0 → user VA, which the MMU resolves via TTBR0.
     *
     * Without this, rosetta stores data via kernel VA (TTBR1) but later
     * reads it via user VA (TTBR0) — the read would fault because TTBR0
     * doesn't cover that address. With TBI1 enabled (TCR_EL1_VALUE_KBUF),
     * the top-byte-ignored kernel VA still translates via TTBR1, while
     * the bits 47:0 extraction translates via TTBR0. Both reach the
     * same physical memory. */
    if (g.kbuf_base) {
        /* Map user VA 0x0000FFFFF0000000 → GPA kbuf_gpa with same
         * permissions as the TTBR1 mapping (initial RW for data). */
        if (guest_map_va_range(&g, KBUF_USER_VA,
                               KBUF_USER_VA + KBUF_SIZE,
                               g.kbuf_gpa, MEM_PERM_RW) < 0) {
            fprintf(stderr, "hl: failed to create kbuf user VA mapping\n");
            guest_destroy(&g);
            return 1;
        }
    }

    /* ---- Step 5b: Record semantic regions for /proc/self/maps ---- */
    guest_region_add(&g, SHIM_BASE, SHIM_BASE + shim_bin_len,
                     LINUX_PROT_READ | LINUX_PROT_EXEC, LINUX_MAP_PRIVATE,
                     0, "[shim]");
    guest_region_add(&g, SHIM_DATA_BASE, SHIM_DATA_BASE + BLOCK_2MB,
                     LINUX_PROT_READ | LINUX_PROT_WRITE, LINUX_MAP_PRIVATE,
                     0, "[shim-data]");

    /* Resolve ELF path for region names */
    char elf_realpath[LINUX_PATH_MAX];
    if (!realpath(elf_path, elf_realpath))
        strncpy(elf_realpath, elf_path, sizeof(elf_realpath) - 1);

    /* In rosetta mode, do NOT register the x86_64 binary segments in
     * regions[]. Rosetta expects to reserve the binary's address range
     * via MAP_FIXED_NOREPLACE and then map the binary itself. If we
     * register the segments, MAP_FIXED_NOREPLACE returns -EEXIST and
     * rosetta aborts with "failed to reserve initial vm for elf".
     *
     * In a real Linux VM with binfmt_misc, the kernel does NOT pre-load
     * the x86_64 binary — it only loads the rosetta interpreter. Rosetta
     * discovers the binary via argv[1] and loads it from scratch.
     *
     * For native aarch64, we always register segments so they appear in
     * /proc/self/maps and prevent mmap overlap. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (elf_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (elf_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g, elf_info.segments[i].gpa + elf_load_base,
                             elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                             prot, LINUX_MAP_PRIVATE,
                             elf_info.segments[i].offset, elf_realpath);
        }
    }

    /* Interpreter semantic regions (if dynamic linking) */
    if (interp_info.num_segments > 0) {
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        for (int i = 0; i < interp_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (interp_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (interp_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g,
                             interp_info.segments[i].gpa + interp_base,
                             interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
                             prot, LINUX_MAP_PRIVATE,
                             interp_info.segments[i].offset, interp_resolved);
        }
    }

    /* Rosetta semantic regions: show the high VA (rosetta's link address)
     * in /proc/self/maps, matching what a real kernel would show. */
    for (int i = 0; i < rosetta_info.num_segments; i++) {
        int prot = LINUX_PROT_READ;
        if (rosetta_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
        if (rosetta_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
        guest_region_add(&g, rosetta_info.segments[i].gpa,
                         rosetta_info.segments[i].gpa + rosetta_info.segments[i].memsz,
                         prot, LINUX_MAP_PRIVATE,
                         rosetta_info.segments[i].offset, ROSETTA_PATH);
    }

    /* Heap starts at brk_base (initially empty, grows via sys_brk) */
    if (g.brk_base < g.brk_current) {
        guest_region_add(&g, g.brk_base, g.brk_current,
                         LINUX_PROT_READ | LINUX_PROT_WRITE,
                         LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                         0, "[heap]");
    }

    /* Stack guard page: PROT_NONE at bottom to catch overflow */
    guest_invalidate_ptes(&g, STACK_BASE, STACK_BASE + STACK_GUARD_SIZE);
    guest_region_add(&g, STACK_BASE, STACK_BASE + STACK_GUARD_SIZE,
                     LINUX_PROT_NONE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack-guard]");
    guest_region_add(&g, STACK_BASE + STACK_GUARD_SIZE, STACK_TOP,
                     LINUX_PROT_READ | LINUX_PROT_WRITE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack]");

    if (verbose) {
        fprintf(stderr, "hl: TTBR0=0x%llx, IPA base=0x%llx\n",
                (unsigned long long)ttbr0, (unsigned long long)g.ipa_base);

        /* Dump page table structure */
        uint64_t l0_off = ttbr0 - g.ipa_base;
        uint64_t *l0 = (uint64_t *)((uint8_t *)g.host_base + l0_off);
        unsigned l0i = (unsigned)(g.ipa_base / (512ULL * 1024 * 1024 * 1024));
        fprintf(stderr, "hl: L0[%u]=0x%llx\n", l0i,
                (unsigned long long)l0[l0i]);

        uint64_t l1_ipa = l0[l0i] & 0xFFFFFFFFF000ULL;
        uint64_t *l1 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l1_ipa - g.ipa_base));
        unsigned l1i = (unsigned)((g.ipa_base % (512ULL * 1024 * 1024 * 1024))
                                  / (1024ULL * 1024 * 1024));
        fprintf(stderr, "hl: L1[%u]=0x%llx\n", l1i,
                (unsigned long long)l1[l1i]);

        uint64_t l2_ipa = l1[l1i] & 0xFFFFFFFFF000ULL;
        uint64_t *l2 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l2_ipa - g.ipa_base));
        for (int i = 0; i < 16; i++) {
            if (l2[i])
                fprintf(stderr, "hl: L2[%d]=0x%llx\n", i,
                        (unsigned long long)l2[i]);
        }
    }

    /* ---- Step 6: Build Linux initial stack ---- */
    syscall_init();
    proc_init();

    /* Record the absolute path of the hl binary itself so that
     * sub-processes (rosettad AOT translation) can invoke it. */
    {
        char self_path[LINUX_PATH_MAX];
        uint32_t path_len = sizeof(self_path);
        if (_NSGetExecutablePath(self_path, &path_len) == 0)
            proc_set_hl_path(self_path);
    }

    proc_set_shim(shim_bin, shim_bin_len);
    /* In rosetta mode, /proc/self/exe must point to rosetta (the
     * interpreter), not the x86_64 binary. This matches real Linux
     * binfmt_misc behavior: the kernel sets exe to the interpreter.
     * Rosetta opens /proc/self/exe to read its own runtime sections
     * (__DATA,runtime_pointers, runtime_syscall, etc.) — returning
     * the x86_64 binary instead causes corrupt internal data structures
     * and "BasicBlock requested for unrecognized address" JIT failures. */
    proc_set_elf_path(need_rosetta ? ROSETTA_PATH : elf_path);
    /* For rosetta mode, record the x86_64 binary path so the rosettad
     * handler thread can perform on-demand AOT translation when the
     * 'd' digest cache misses. In real VZ VMs, rosettad pre-caches
     * AOT translations so 'd' always hits. We match that behavior by
     * translating on-the-fly during the 'd' request. */
    if (need_rosetta) {
        extern void rosettad_set_binary_path(const char *path);
        rosettad_set_binary_path(elf_realpath);
    }
    proc_set_cmdline(guest_argc, guest_argv);
    if (sysroot)
        proc_set_sysroot(sysroot);
    extern const char **environ;
    uint64_t sp;
    uint64_t entry_point;

    /* Build vDSO for rosetta (must happen before stack building since
     * AT_SYSINFO_EHDR in the auxv points to the vDSO ELF header) */
    uint64_t vdso_addr = 0;
    if (need_rosetta) {
        vdso_addr = vdso_build(&g);
        if (!vdso_addr) {
            fprintf(stderr, "hl: failed to build vDSO\n");
            guest_destroy(&g);
            return 1;
        }
        /* Register [vvar] and [vdso] in the region table so they
         * appear in /proc/self/maps. Real Linux VMs have both entries;
         * rosetta's VMAllocationTracker parses maps at startup and
         * uses it to build its initial memory layout knowledge.
         * [vvar] is a read-only page placed immediately before [vdso]. */
        guest_region_add(&g, VDSO_BASE - 0x1000,
                         VDSO_BASE,
                         LINUX_PROT_READ, LINUX_MAP_PRIVATE,
                         0, "[vvar]");
        guest_region_add(&g, VDSO_BASE,
                         VDSO_BASE + VDSO_SIZE,
                         LINUX_PROT_READ | LINUX_PROT_EXEC,
                         LINUX_MAP_PRIVATE,
                         0, "[vdso]");
        if (verbose)
            fprintf(stderr, "hl: vDSO built at 0x%llx\n",
                    (unsigned long long)vdso_addr);
    }

    if (need_rosetta) {
        /* Rosetta mode: build argv similar to binfmt_misc.
         * Rosetta passes argv[1] directly as the translated program's
         * argv[0], so we use the real binary path (not /proc/self/fd/N)
         * so that programs like busybox can determine their applet name
         * via basename(argv[0]).  The binary is also pre-opened at fd 3
         * for rosetta to mmap during translation. */
        int bin_host_fd = open(elf_realpath, O_RDONLY);
        if (bin_host_fd < 0) {
            fprintf(stderr, "hl: failed to pre-open binary: %s\n", elf_realpath);
            guest_destroy(&g);
            return 1;
        }
        int bin_guest_fd = fd_alloc_at(3, FD_REGULAR, bin_host_fd);
        if (bin_guest_fd < 0) {
            fprintf(stderr, "hl: failed to allocate fd 3 for binary\n");
            close(bin_host_fd);
            guest_destroy(&g);
            return 1;
        }

        /* Rosetta passes argv[1] directly as the translated program's
         * argv[0].  We pass the real binary path here so the translated
         * program sees the correct name (e.g., busybox uses basename(argv[0])
         * for applet lookup).  The binary is also pre-opened at fd 3 for
         * rosetta's internal use (it opens argv[1] and mmaps the ELF). */
        int rosetta_argc = guest_argc + 1;  /* rosetta_path + binary_path + original_argv[1:] */
        const char **rosetta_argv = malloc(sizeof(char *) * (rosetta_argc + 1));
        if (!rosetta_argv) {
            fprintf(stderr, "hl: malloc failed for rosetta argv\n");
            guest_destroy(&g);
            return 1;
        }
        rosetta_argv[0] = ROSETTA_PATH;
        rosetta_argv[1] = elf_realpath;
        for (int i = 1; i < guest_argc; i++)
            rosetta_argv[i + 1] = guest_argv[i];
        rosetta_argv[rosetta_argc] = NULL;

        /* Stack auxv describes rosetta as the main binary (binfmt_misc
         * semantics: the interpreter IS the main binary from the kernel's
         * perspective). AT_PHDR/PHENT/PHNUM/ENTRY all refer to rosetta.
         * Rosetta finds the x86_64 binary via argv[1]. */
        sp = build_linux_stack(&g, STACK_TOP,
                               rosetta_argc, rosetta_argv,
                               environ, &rosetta_info,
                               0 /* rosetta is ET_EXEC at link addr */,
                               0 /* no dynamic linker for rosetta */,
                               vdso_addr,
                               3 /* AT_EXECFD: binary pre-opened at fd 3 */);
        free(rosetta_argv);

        /* Entry point: rosetta entry (at high IPA) */
        entry_point = rosetta_info.entry;
    } else {
        /* Normal aarch64 mode */
        sp = build_linux_stack(&g, STACK_TOP,
                               guest_argc, guest_argv,
                               environ, &elf_info,
                               elf_load_base, interp_base,
                               0 /* no vDSO for aarch64 */,
                               -1 /* no AT_EXECFD */);

        /* Entry point: interpreter entry if dynamic, ELF entry if static.
         * For PIE (ET_DYN), elf_info.entry is relative, needs elf_load_base. */
        entry_point = (interp_base != 0)
            ? (interp_info.entry + interp_base)
            : (elf_info.entry + elf_load_base);
    }

    if (verbose) {
        fprintf(stderr, "hl: SP=0x%llx, entry=0x%llx%s\n",
                (unsigned long long)sp,
                (unsigned long long)entry_point,
                need_rosetta ? " (via rosetta)" :
                interp_base ? " (via interpreter)" : "");
    }

    /* ---- Step 7: Create vCPU and configure registers ---- */
    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    HV_CHECK(hv_vcpu_create(&vcpu, &vexit, NULL));
    g.vcpu = vcpu;
    g.exit = vexit;

    /* All guest-visible addresses are IPA-based: GUEST_IPA_BASE + offset */
    uint64_t shim_ipa  = guest_ipa(&g, SHIM_BASE);
    uint64_t entry_ipa = guest_ipa(&g, entry_point);
    uint64_t sp_ipa    = guest_ipa(&g, sp);
    uint64_t el1_sp    = guest_ipa(&g, SHIM_DATA_BASE + BLOCK_2MB);

    /* Register main thread in the thread table (before entering run loop) */
    thread_register_main(vcpu, vexit, proc_get_pid(), el1_sp);

    /* -- System registers (all set from host, no HVC #4 in shim) -- */

    /* VBAR_EL1: vector table at shim_base + 0x800 (.align 11 offset) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_VBAR_EL1,
                                 shim_ipa + 0x800));

    /* MAIR_EL1: Attr0=Device-nGnRnE (0x00), Attr1=Normal WB (0xFF) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_MAIR_EL1, 0xFF00));

    /* TCR_EL1: 4KB granule, 48-bit VA.
     * When kernel VA buffer is active (rosetta mode), enable TTBR1 walks
     * (EPD1=0) so kernel-space addresses are translated via TTBR1. */
    uint64_t tcr_value = g.kbuf_base ? TCR_EL1_VALUE_KBUF : TCR_EL1_VALUE;
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TCR_EL1, tcr_value));

    /* TTBR0_EL1: page table base (IPA from guest_build_page_tables) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR0_EL1, ttbr0));

    /* TTBR1_EL1: kernel VA page tables (rosetta mode) or unused */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR1_EL1,
                                  g.ttbr1 ? g.ttbr1 : 0));

    /* CPACR_EL1: enable FP/SIMD at EL0 and EL1 (FPEN=0b11) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_CPACR_EL1, 3ULL << 20));

    /* ELR_EL1: EL0 entry point (shim will ERET to this address) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_ELR_EL1, entry_ipa));

    /* SPSR_EL1: EL0t, AArch64, all interrupts masked on entry */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SPSR_EL1, 0x0));

    /* SP_EL0: initial stack pointer for EL0 */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL0, sp_ipa));

    /* SP_EL1: EL1 stack for exception handlers (top of shim data region) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL1, el1_sp));

    /* SCTLR_EL1: read default, then enable MMU + caches */
    uint64_t sctlr;
    HV_CHECK(hv_vcpu_get_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, &sctlr));
    if (verbose)
        fprintf(stderr, "hl: SCTLR_EL1 default=0x%llx\n",
                (unsigned long long)sctlr);

    /* Build a proper SCTLR with RES1 bits + caches, but WITHOUT MMU enable.
     * Apple's HVF requires the MMU to be enabled DURING vCPU execution
     * (via HVC #4 from the shim), not before hv_vcpu_run. Setting SCTLR.M=1
     * via hv_vcpu_set_sys_reg before start causes permission faults.
     * The shim will HVC #4 to enable M after TLBI/DSB/ISB. */
    sctlr = SCTLR_RES1 | SCTLR_C | SCTLR_I
          | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;  /* No SCTLR_M here */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, sctlr));

    /* -- General purpose registers -- */

    /* PC = shim entry (TLBI + zero regs + ERET) */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_PC, shim_ipa));

    /* CPSR = EL1h (0x3c5) — shim runs at EL1 */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_CPSR, 0x3c5));

    /* Zero all general purpose registers */
    for (int i = 0; i < 31; i++) {
        HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0 + i, 0));
    }

    /* Pass the full SCTLR value (WITH M=1) in X0 for the shim to
     * enable the MMU during execution via HVC #4. */
    uint64_t sctlr_with_mmu = SCTLR_RES1 | SCTLR_M | SCTLR_C | SCTLR_I
                            | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0, sctlr_with_mmu));

    if (verbose) {
        fprintf(stderr, "hl: vCPU configured: PC=0x%llx SCTLR=0x%llx "
                "VBAR=0x%llx TTBR0=0x%llx TCR=0x%llx\n",
                (unsigned long long)shim_ipa,
                (unsigned long long)sctlr,
                (unsigned long long)(shim_ipa + 0x800),
                (unsigned long long)ttbr0,
                (unsigned long long)tcr_value);
        fprintf(stderr, "hl: ELR_EL1=0x%llx SP_EL0=0x%llx SP_EL1=0x%llx\n",
                (unsigned long long)entry_ipa,
                (unsigned long long)sp_ipa,
                (unsigned long long)el1_sp);
    }

    /* ---- Step 8: vCPU execution loop ---- */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec);

    /* ---- Cleanup ---- */
    guest_destroy(&g);

    return exit_code;
}
