/* hl.c — Run aarch64-linux and x86_64-linux ELF binaries on macOS Apple Silicon
 *
 * Copyright 2025 Moritz Angermann <moritz@zw3rk.com>, zw3rk pte. ltd.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Uses Hypervisor.framework to create a lightweight VM with:
 *   - A minimal EL1 shim (embedded as shim_blob.h) that provides exception
 *     vectors and forwards SVC #0 (Linux syscalls) to the host via HVC #5.
 *   - All system registers configured from the host before vCPU start.
 *   - Guest memory identity-mapped at GVA=GPA with 2MB block page tables.
 *   - Syscall handlers that translate Linux syscalls to macOS equivalents.
 *   - x86_64-linux support via Apple's Rosetta Linux translator, which
 *     JIT-translates x86_64 instructions to ARM64 syscalls transparently.
 *
 * Usage: hl [--verbose] [--timeout N] [--sysroot PATH] <elf-path> [args...]
 */
#include <Hypervisor/Hypervisor.h>
#include <Hypervisor/hv_vcpu.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <pthread.h>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include <libkern/OSCacheControl.h>
#include <mach-o/dyld.h>

#include "guest.h"
#include "elf.h"
#include "syscall.h"
#include "syscall_internal.h"  /* LINUX_PATH_MAX (for elf_path realpath) */
#include "syscall_proc.h"
#include "hv_util.h"
#include "fork_ipc.h"
#include "stack.h"
#include "vdso.h"
#include "thread.h"
#include "rosetta.h"
#include "gdb_stub.h"
#include "trace.h"
#include "syscall_stats.h"
#include "vfs.h"
#include "audio.h"

/* Embedded shim binary (generated by xxd -i from shim.bin) */
#include "shim_blob.h"

/* Build-time version string (generated by make into _build/version.h) */
#include "version.h"

/* ---------- Main ---------- */

int main(int argc, char **argv) {
    /* Ignore host SIGPIPE. The guest's SIGPIPE is emulated: write()/send()
     * handlers translate EPIPE into signal_queue(LINUX_SIGPIPE). Without
     * this, the host write() inside those handlers is killed by SIGPIPE
     * before it can return EPIPE, so the whole VM dies (exit 141) and the
     * emulation is unreachable. Applies to the normal, --fork-child and
     * rosettad paths alike, and is inherited across posix_spawn. */
    signal(SIGPIPE, SIG_IGN);

    int verbose = 0;
    /* Watchdog OFF by default (0). It armed alarm() per hv_vcpu_run()
     * iteration, so a 10s default killed every compute-bound or
     * vDSO-time-polling guest. --timeout N (N>0) opts in to a coarse
     * hang detector on the main vCPU; 0 disables it. */
    int timeout_sec = 0;
    int fork_child_fd = -1; /* IPC fd for --fork-child mode */
    const char *sysroot = NULL; /* Sysroot for dynamic linker resolution */
    int gdb_port = 0;         /* GDB RSP port (0 = disabled) */
    int gdb_stop_on_entry = 0; /* Wait for GDB attach before executing */
    int arg_start = 1;
    /* Profile defaults (applied after option parse unless overridden):
     *   --fs-mode=rooted --bind $HOME:/home/user --guest-cwd /home/user
     *   --audio-backend=coreaudio
     * --isolated skips auto $HOME bind and auto guest-cwd. */
    int isolated = 0;
    int fs_mode_set = 0;
    int audio_backend_set = 0;
    int guest_cwd_set = 0;
    int home_bind_set = 0;
    int tmp_bind_set = 0;

    /* Handle --version / --help before option parsing */
    if (argc > 1) {
        if (strcmp(argv[1], "--version") == 0 || strcmp(argv[1], "-V") == 0) {
            printf("hl %s\n", HL_VERSION);
            return 0;
        }
        if (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
            /* Locate man page relative to binary.  execlp replaces the
             * process, so we must check access() before each attempt —
             * once man(1) runs, there is no fallback. */
            char man_path[4096];
            const char *slash = strrchr(argv[0], '/');
            if (slash) {
                int dirlen = (int)(slash - argv[0]);
                /* Installed: <bindir>/../share/man/man1/hl.1 */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../share/man/man1/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Source tree: <bindir>/../hl.1  (binary in _build/) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/../hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
                /* Distribution zip: <bindir>/hl.1  (binary and man page side by side) */
                snprintf(man_path, sizeof(man_path),
                         "%.*s/hl.1", dirlen, argv[0]);
                if (access(man_path, R_OK) == 0)
                    execlp("man", "man", man_path, (char *)NULL);
            }
            /* System man path (last resort — replaces process) */
            execlp("man", "man", "1", "hl", (char *)NULL);
            /* man not available at all */
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] [--fs-mode legacy|rooted] "
                    "[--bind HOST:GUEST] [--isolated] [--audio-backend NAME] "
                    "[--gdb PORT] [--gdb-stop-on-entry] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Category tracing: env first, then --trace ORs in. */
    if (hl_trace_init_from_env() < 0)
        return 1;
    hl_vfs_init_defaults();
    /* HL_AUDIO_BACKEND env is applied in hl_audio_init(); track if set. */
    if (getenv("HL_AUDIO_BACKEND") && getenv("HL_AUDIO_BACKEND")[0])
        audio_backend_set = 1;

    /* Parse hl options */
    while (arg_start < argc && argv[arg_start][0] == '-') {
        if (strcmp(argv[arg_start], "--verbose") == 0 ||
            strcmp(argv[arg_start], "-v") == 0) {
            verbose = 1;
            hl_verbose = 1;  /* Global flag for detached threads */
            arg_start++;
        } else if ((strcmp(argv[arg_start], "--timeout") == 0 ||
                    strcmp(argv[arg_start], "-t") == 0) &&
                   arg_start + 1 < argc) {
            /* Checked parse: 0 = off, N>0 = arm; reject junk/negative/overflow
             * rather than silently snapping to a default. */
            {
                char *end = NULL;
                errno = 0;
                long v = strtol(argv[arg_start + 1], &end, 10);
                if (errno != 0 || !end || *end != '\0' || v < 0 || v > 86400) {
                    fprintf(stderr, "hl: --timeout: invalid value '%s' "
                            "(expected 0..86400 seconds; 0 = off)\n",
                            argv[arg_start + 1]);
                    return 1;
                }
                timeout_sec = (int)v;
            }
            hl_watchdog_timeout_sec = timeout_sec; /* for fork-child argv */
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--fork-child") == 0 &&
                   arg_start + 1 < argc) {
            fork_child_fd = atoi(argv[arg_start + 1]);
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--sysroot") == 0 &&
                   arg_start + 1 < argc) {
            sysroot = argv[arg_start + 1];
            hl_vfs_set_sysroot(sysroot);
            proc_set_sysroot(sysroot); /* early: openat sysroot fallback needs it */
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--fs-mode") == 0 &&
                   arg_start + 1 < argc) {
            hl_fs_mode_t mode;
            if (hl_vfs_parse_mode(argv[arg_start + 1], &mode) < 0) {
                fprintf(stderr, "hl: invalid --fs-mode=%s (use legacy|rooted)\n",
                        argv[arg_start + 1]);
                return 1;
            }
            hl_vfs_set_mode(mode);
            fs_mode_set = 1;
            arg_start += 2;
        } else if (strncmp(argv[arg_start], "--fs-mode=", 10) == 0) {
            hl_fs_mode_t mode;
            if (hl_vfs_parse_mode(argv[arg_start] + 10, &mode) < 0) {
                fprintf(stderr, "hl: invalid %s (use legacy|rooted)\n",
                        argv[arg_start]);
                return 1;
            }
            hl_vfs_set_mode(mode);
            fs_mode_set = 1;
            arg_start++;
        } else if (strcmp(argv[arg_start], "--bind") == 0 &&
                   arg_start + 1 < argc) {
            if (hl_vfs_parse_bind_arg(argv[arg_start + 1]) < 0) {
                fprintf(stderr, "hl: invalid --bind %s (use HOST:GUEST or GUEST=HOST)\n",
                        argv[arg_start + 1]);
                return 1;
            }
            /* Inspect the parsed guest prefix, not the raw spec: host paths
             * may themselves contain strings such as "/tmp". */
            const hl_vfs_t *vfs = hl_vfs_get();
            const char *guest_prefix =
                vfs->mounts[vfs->nmounts - 1].guest_prefix;
            if (strcmp(guest_prefix, "/home/user") == 0)
                home_bind_set = 1;
            if (strcmp(guest_prefix, "/tmp") == 0)
                tmp_bind_set = 1;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--guest-home") == 0 &&
                   arg_start + 1 < argc) {
            hl_vfs_set_guest_home(argv[arg_start + 1]);
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--guest-cwd") == 0 &&
                   arg_start + 1 < argc) {
            hl_vfs_set_cwd(argv[arg_start + 1]);
            guest_cwd_set = 1;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--app-profile") == 0) {
            hl_vfs_apply_app_profile(NULL);
            fs_mode_set = 1;
            home_bind_set = 1;
            guest_cwd_set = 1;
            arg_start++;
        } else if (strcmp(argv[arg_start], "--isolated") == 0) {
            /* No auto $HOME→/home/user bind / guest-cwd defaults. */
            isolated = 1;
            arg_start++;
        } else if (strcmp(argv[arg_start], "--trace") == 0 &&
                   arg_start + 1 < argc) {
            char err[256];
            if (hl_trace_enable(argv[arg_start + 1], err, sizeof(err)) < 0) {
                fprintf(stderr, "hl: --trace: %s\n", err);
                return 1;
            }
            arg_start += 2;
        } else if (strncmp(argv[arg_start], "--trace=", 8) == 0) {
            char err[256];
            if (hl_trace_enable(argv[arg_start] + 8, err, sizeof(err)) < 0) {
                fprintf(stderr, "hl: --trace: %s\n", err);
                return 1;
            }
            arg_start++;
        } else if (strcmp(argv[arg_start], "--audio-backend") == 0 &&
                   arg_start + 1 < argc) {
            if (hl_audio_set_backend_name(argv[arg_start + 1]) < 0) {
                fprintf(stderr, "hl: invalid --audio-backend=%s "
                        "(null|null-realtime|wav|coreaudio)\n",
                        argv[arg_start + 1]);
                return 1;
            }
            /* Flag wins over HL_AUDIO_BACKEND, which hl_audio_init() reads
             * later from syscall_init(). */
            hl_audio_set_backend_explicit();
            audio_backend_set = 1;
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--gdb") == 0 &&
                   arg_start + 1 < argc) {
            gdb_port = atoi(argv[arg_start + 1]);
            if (gdb_port <= 0 || gdb_port > 65535) {
                fprintf(stderr, "hl: invalid GDB port: %s\n",
                        argv[arg_start + 1]);
                return 1;
            }
            arg_start += 2;
        } else if (strcmp(argv[arg_start], "--gdb-stop-on-entry") == 0) {
            gdb_stop_on_entry = 1;
            arg_start++;
        } else if (strcmp(argv[arg_start], "--") == 0) {
            arg_start++;
            break;
        } else {
            fprintf(stderr, "hl: unknown option: %s\n", argv[arg_start]);
            fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                    "[--sysroot PATH] [--fs-mode legacy|rooted] [--bind HOST:GUEST] "
                    "[--isolated] [--trace=fs,fd,dev,audio,proc,fork,sys] "
                    "[--audio-backend NAME] "
                    "[--gdb PORT] [--gdb-stop-on-entry] <elf-path> [args...]\n");
            return 1;
        }
    }

    /* Syscall volume profiling: HL_SYSCALL_STATS=1 or HL_TRACE=sys / --trace=sys */
    syscall_stats_init();
    syscall_stats_install_signal();
    syscall_stats_atexit_register();

    /* Fork-child mode: receive VM state over IPC and run.
     * Do not apply host profile defaults — child imports VFS from parent. */
    if (fork_child_fd >= 0)
        return fork_child_main(fork_child_fd, verbose, timeout_sec);

    /* ---- Default profile (interactive / product path) ---- */
    if (!fs_mode_set)
        hl_vfs_set_mode(HL_FS_ROOTED);

    if (!audio_backend_set)
        hl_audio_set_backend(HL_AUDIO_BACKEND_COREAUDIO);

    if (!isolated && hl_vfs_mode() == HL_FS_ROOTED) {
        const char *home = getenv("HOME");
        if (home && home[0] && !home_bind_set) {
            char bind_arg[HL_VFS_PATH_MAX * 2];
            /* HOST:GUEST form */
            snprintf(bind_arg, sizeof(bind_arg), "%s:/home/user", home);
            if (hl_vfs_parse_bind_arg(bind_arg) < 0) {
                fprintf(stderr, "hl: failed default bind %s\n", bind_arg);
                return 1;
            }
            hl_vfs_set_guest_home("/home/user");
            home_bind_set = 1;
        }
        /* Prefer Music for guest CWD: GTK file dialogs list CWD/HOME, and
         * a full macOS home (Library, iCloud/FileProvider) can hang on
         * stat of cloud placeholders. Music is the usual media root. */
        if (!guest_cwd_set && home_bind_set) {
            const char *home2 = getenv("HOME");
            char music_host[LINUX_PATH_MAX];
            if (home2) {
                snprintf(music_host, sizeof(music_host), "%s/Music", home2);
                if (access(music_host, F_OK) == 0)
                    hl_vfs_set_cwd("/home/user/Music");
                else
                    hl_vfs_set_cwd("/home/user");
            } else {
                hl_vfs_set_cwd("/home/user");
            }
        }
    }

    /* Rooted + --sysroot: expose the sysroot as guest /sysroot so the
     * dynamic linker can open libraries via a normal mount (and via
     * LD_LIBRARY_PATH=/sysroot/lib). Without this, absolute nix RUNPATHs
     * fall outside every bind and library loads fail with
     * "cannot open shared object file". */
    if (sysroot && sysroot[0] && hl_vfs_mode() == HL_FS_ROOTED) {
        char libcheck[LINUX_PATH_MAX];
        snprintf(libcheck, sizeof(libcheck), "%s/lib", sysroot);
        if (access(libcheck, F_OK) != 0) {
            fprintf(stderr,
                    "hl: warning: --sysroot %s has no lib/ directory\n",
                    sysroot);
        }
        if (hl_vfs_add_bind("/sysroot", sysroot, HL_MOUNT_RO) < 0) {
            fprintf(stderr, "hl: failed to bind sysroot at /sysroot\n");
            return 1;
        }
        if (verbose)
            fprintf(stderr, "hl: bound %s → /sysroot (ro)\n", sysroot);
    }

    /* Nix store: plugins and RPATH dirs are absolute /nix/store/... paths
     * (e.g. xmms PLUGINDIR .../lib/xmms/Input). Basename sysroot fallback
     * only works for flat lib sonames, not multi-component plugin trees. */
    int nix_store_bound = 0;
    if (!isolated && hl_vfs_mode() == HL_FS_ROOTED &&
        access("/nix/store", F_OK) == 0) {
        if (hl_vfs_add_bind("/nix/store", "/nix/store", HL_MOUNT_RO) == 0) {
            nix_store_bound = 1;
            if (verbose)
                fprintf(stderr, "hl: bound /nix/store -> /nix/store (ro)\n");
        }
    }

    /* /tmp: control sockets (xmms_user.0), GTK temp files. macOS TMPDIR
     * is under /var/folders/... which is not mounted by default. */
    int tmp_bound = tmp_bind_set;
    if (!tmp_bound && !isolated && hl_vfs_mode() == HL_FS_ROOTED &&
        access("/tmp", F_OK) == 0) {
        if (hl_vfs_add_bind("/tmp", "/tmp", 0) == 0) {
            tmp_bound = 1;
            if (verbose)
                fprintf(stderr, "hl: bound /tmp -> /tmp\n");
        }
    }

    /* X11 / XQuartz: Linux clients use DISPLAY=:0 -> /tmp/.X11-unix/X0.
     * macOS sets DISPLAY to a launchd socket path (org.xquartz:0 under
     * /var/run/com.apple.launchd....) which works for native XQuartz
     * clients but not for Linux libX11. Bind the Unix socket dir and
     * normalize DISPLAY in the guest env below. */
    int x11_socket_bound = 0;
    if (!isolated && hl_vfs_mode() == HL_FS_ROOTED &&
        access("/tmp/.X11-unix", F_OK) == 0) {
        if (hl_vfs_add_bind("/tmp/.X11-unix", "/tmp/.X11-unix", 0) == 0) {
            x11_socket_bound = 1;
            if (verbose)
                fprintf(stderr, "hl: bound /tmp/.X11-unix -> /tmp/.X11-unix\n");
        }
    }
    (void)nix_store_bound;

    if (arg_start >= argc) {
        fprintf(stderr, "usage: hl [--verbose] [--timeout N] "
                "[--sysroot PATH] [--fs-mode legacy|rooted] [--bind HOST:GUEST] "
                "[--isolated] [--audio-backend NAME] <elf-path> [args...]\n");
        return 1;
    }

    /* Copy elf_path, sysroot, and guest_argv to heap — the original argv
     * string data lives in a contiguous stack region that we clobber below
     * for the process title (PostgreSQL/nginx argv-clobber technique).
     * Without this, --sysroot becomes "" after the clobber and dynamic
     * linking falls apart (libgtk-1.2.so.0 not found, etc.). */
    const char *elf_path = strdup(argv[arg_start]);
    if (!elf_path) {
        fprintf(stderr, "hl: out of memory\n");
        return 1;
    }
    if (sysroot && sysroot[0]) {
        char *sysroot_owned = strdup(sysroot);
        if (!sysroot_owned) {
            fprintf(stderr, "hl: out of memory\n");
            return 1;
        }
        sysroot = sysroot_owned;
        /* Refresh copies that were taken from the soon-to-be-clobbered argv. */
        hl_vfs_set_sysroot(sysroot);
        proc_set_sysroot(sysroot);
    } else {
        sysroot = NULL;
    }
    int guest_argc = argc - arg_start;
    const char **guest_argv = malloc(guest_argc * sizeof(char *));
    if (!guest_argv) {
        fprintf(stderr, "hl: out of memory building guest argv\n");
        return 1;
    }
    for (int i = 0; i < guest_argc; i++) {
        guest_argv[i] = strdup(argv[arg_start + i]);
        if (!guest_argv[i]) {
            fprintf(stderr, "hl: out of memory building guest argv\n");
            return 1;
        }
    }

    /* ---- Step 1: Load and parse ELF ---- */
    elf_info_t elf_info;
    if (elf_load(elf_path, &elf_info) < 0) {
        fprintf(stderr, "hl: failed to load ELF: %s\n", elf_path);
        return 1;
    }

    if (verbose) {
        fprintf(stderr, "hl: ELF entry=0x%llx, %d segments, "
                "load range [0x%llx, 0x%llx), machine=%s\n",
                (unsigned long long)elf_info.entry,
                elf_info.num_segments,
                (unsigned long long)elf_info.load_min,
                (unsigned long long)elf_info.load_max,
                elf_info.e_machine == EM_AARCH64 ? "aarch64" : "x86_64");
    }

    /* ---- Step 1b: Detect x86_64 ---- */
    int need_rosetta = (elf_info.e_machine == EM_X86_64);
    rosetta_result_t rr;
    memset(&rr, 0, sizeof(rr));

    /* ---- Step 2: Initialize guest memory and VM ---- */
    /* Rosetta requests as much IPA as the host grants (ceiling 48), which
     * guest_init caps to the host max (40-bit / 1TB on macOS 26). That 1TB
     * primary is the whole guest-physical window: rosetta's binary (linked at
     * VA 128TB), its high-VA JIT/AOT/PIE regions, and the x86_64 target are all
     * mapped to LOW IPAs inside it (rosetta.c / the high-VA mmap packer), so no
     * >40-bit IPA is needed. The explicit is_rosetta flag keeps the file-backed
     * COW path (a 1TB ftruncate) off, since rosetta forks via the IPC copy path.
     * For native aarch64, auto-detect (36/40-bit) is sufficient. */
    guest_t g;
    if (guest_init(&g, 0, need_rosetta ? 48 : 0, need_rosetta) < 0) {
        fprintf(stderr, "hl: failed to initialize guest\n");
        return 1;
    }
    g.is_rosetta = need_rosetta;
    g.verbose = verbose;

    /* Set process title so ps/Activity Monitor show the guest binary name
     * instead of "hl" (e.g. "grep (x86_64-linux)").
     *
     * Three mechanisms (following PostgreSQL/nginx convention):
     * - argv[0] clobber: macOS ps reads live from KERN_PROCARGS2, so
     *   overwriting the contiguous argv+environ area on the stack changes
     *   what `ps -o comm` and `ps -o args` display.
     * - kern.procname sysctl: writes the kernel p_name field (pbi_name),
     *   which Activity Monitor reads via proc_pidinfo(PROC_PIDTBSDINFO).
     * - setprogname: updates libc getprogname() and crash reports.
     * - pthread_setname_np: sets main thread name (Instruments, lldb). */
    {
        const char *slash = strrchr(elf_path, '/');
        const char *bin = slash ? slash + 1 : elf_path;
        const char *arch = need_rosetta ? "x86_64" : "aarch64";
        char title[256];
        snprintf(title, sizeof(title), "%s (%s-linux)", bin, arch);

        /* Write kernel p_name (up to 2*MAXCOMLEN=32 chars) so Activity
         * Monitor picks up the guest binary name. setprogname() only
         * sets the libc-internal __progname and does NOT touch the kernel. */
        sysctlbyname("kern.procname", NULL, NULL, title, strlen(title));
        setprogname(title);

        char thread_name[64];
        snprintf(thread_name, sizeof(thread_name), "%s (%s-linux)",
                 bin, arch);
        pthread_setname_np(thread_name);

        /* Clobber argv[0] with the new title. On macOS, argv and environ
         * strings are contiguous on the stack. We compute the total available
         * buffer from argv[0] through the end of the last environ string,
         * copy environ to the heap first (so getenv() keeps working), then
         * overwrite the entire region with our title. */
        extern char **environ;
        if (argv[0] != NULL && environ != NULL) {
            /* Find the end of the contiguous argv+environ area */
            char *argv_end = argv[0];
            for (int i = 0; i < argc; i++) {
                if (argv[i] != NULL) {
                    char *p = argv[i] + strlen(argv[i]) + 1;
                    if (p > argv_end) argv_end = p;
                }
            }
            for (int i = 0; environ[i] != NULL; i++) {
                char *p = environ[i] + strlen(environ[i]) + 1;
                if (p > argv_end) argv_end = p;
            }
            size_t avail = (size_t)(argv_end - argv[0]);

            /* Copy environ to heap so getenv() survives the clobber */
            int env_count = 0;
            while (environ[env_count]) env_count++;
            char **new_environ = malloc((env_count + 1) * sizeof(char *));
            if (new_environ) {
                /* A NULL from strdup would TERMINATE the copied environment
                 * at that point, silently losing every later variable — so
                 * keep the original on failure rather than half of it. */
                int ok = 1;
                for (int i = 0; i < env_count && ok; i++) {
                    new_environ[i] = strdup(environ[i]);
                    if (!new_environ[i]) {
                        for (int k = 0; k < i; k++) free(new_environ[k]);
                        free(new_environ);
                        new_environ = NULL;
                        ok = 0;
                    }
                }
                if (ok) {
                    new_environ[env_count] = NULL;
                    environ = new_environ;
                }
            }

            /* Only clobber the original argv+environ area once environ has
             * been safely relocated to the heap. `avail` spans through the
             * last environ string, so the memset below would otherwise WIPE
             * the live environment when the strdup copy failed (OOM) — every
             * later getenv() would then return garbage. Skip the cosmetic
             * title rewrite in that case; a valid environment matters more. */
            if (environ == new_environ && new_environ != NULL) {
                size_t title_len = strlen(title);
                if (title_len < avail) {
                    memcpy(argv[0], title, title_len);
                    memset(argv[0] + title_len, '\0', avail - title_len);
                }
                /* Null out remaining argv pointers so ps doesn't show stale args */
                for (int i = 1; i < argc; i++)
                    argv[i] = NULL;
            }
        }
    }

    if (verbose) {
        fprintf(stderr, "hl: IPA size: %u bits (%lluGB primary)\n",
                g.ipa_bits,
                (unsigned long long)(g.guest_size / (1024ULL * 1024 * 1024)));
    }

    /* ---- Step 3: Load ELF segments into guest memory ---- */
    /* PIE executables (ET_DYN) have virtual addresses starting near 0,
     * which would overlap with the page table pool and shim. Load them
     * at PIE_LOAD_BASE (0x400000) instead. ET_EXEC binaries already
     * have absolute addresses (typically 0x400000+), so use base 0. */
    uint64_t elf_load_base = (elf_info.e_type == ET_DYN) ? PIE_LOAD_BASE : 0;

    /* Map ELF segments into guest memory. For x86_64 binaries, the kernel
     * would have already mapped the binary before launching Rosetta as the
     * binfmt_misc interpreter. Rosetta reads /proc/self/maps to discover
     * the binary layout, then either reuses existing mappings or re-maps
     * via MAP_FIXED. Pre-mapping ensures correct /proc/self/maps output
     * and consistent binary data in guest memory. */
    if (elf_map_segments(&elf_info, elf_path,
                         g.host_base, g.guest_size, elf_load_base) < 0) {
        fprintf(stderr, "hl: failed to map ELF segments\n");
        guest_destroy(&g);
        return 1;
    }

    /* Set brk base after the highest loaded segment. */
    uint64_t brk_start = (elf_info.load_max + elf_load_base + 4095) & ~4095ULL;
    if (brk_start < BRK_BASE_DEFAULT)
        brk_start = BRK_BASE_DEFAULT;
    g.brk_base = brk_start;
    g.brk_current = brk_start;

    /* Place stack above brk, 2MB-aligned.  For small binaries the stack
     * stays at the default 256MB position.  For large binaries (e.g.,
     * 200MB pandoc) the stack moves up so it doesn't overlap the binary's
     * address space — rosetta uses MAP_FIXED_NOREPLACE to reserve the
     * binary range and will fail with EEXIST if the stack is in the way. */
    uint64_t stack_top = (brk_start + BLOCK_2MB - 1) & ~(BLOCK_2MB - 1);
    stack_top += STACK_SIZE;                     /* room for 8MB stack */
    if (stack_top < STACK_TOP_DEFAULT)
        stack_top = STACK_TOP_DEFAULT;
    g.stack_top  = stack_top;
    g.stack_base = stack_top - STACK_SIZE;

    /* ---- Step 3b: Load dynamic linker if PT_INTERP present ---- */
    elf_info_t interp_info;
    uint64_t interp_base = 0;
    memset(&interp_info, 0, sizeof(interp_info));

    /* Skip PT_INTERP for x86_64 + rosetta: rosetta handles x86_64
     * dynamic linking internally (loading ld-linux-x86-64.so.2 etc.).
     * We only handle aarch64 interpreters here. */
    if (!need_rosetta && elf_info.interp_path[0] != '\0') {
        /* Resolve interpreter path, applying sysroot if set */
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        if (verbose)
            fprintf(stderr, "hl: loading interpreter: %s\n", interp_resolved);

        if (elf_load(interp_resolved, &interp_info) < 0) {
            fprintf(stderr, "hl: failed to load interpreter: %s\n",
                    interp_resolved);
            guest_destroy(&g);
            return 1;
        }

        /* Load interpreter at dynamic interp_base (computed from guest_size) */
        interp_base = g.interp_base;
        if (elf_map_segments(&interp_info, interp_resolved,
                             g.host_base, g.guest_size, interp_base) < 0) {
            fprintf(stderr, "hl: failed to map interpreter segments\n");
            guest_destroy(&g);
            return 1;
        }

        if (verbose) {
            fprintf(stderr, "hl: interpreter loaded at base=0x%llx, "
                    "entry=0x%llx, %d segments\n",
                    (unsigned long long)interp_base,
                    (unsigned long long)(interp_info.entry + interp_base),
                    interp_info.num_segments);
        }
    }

    /* ---- Step 4: Load shim into guest at SHIM_BASE ---- */
    if (shim_bin_len > BLOCK_2MB) {
        fprintf(stderr, "hl: shim binary too large (%u bytes)\n", shim_bin_len);
        guest_destroy(&g);
        return 1;
    }
    memcpy((uint8_t *)g.host_base + SHIM_BASE, shim_bin, shim_bin_len);

    if (verbose) {
        fprintf(stderr, "hl: shim loaded at offset 0x%llx (%u bytes)\n",
                (unsigned long long)SHIM_BASE, shim_bin_len);
    }

    /* ---- Step 4b: Invalidate I-cache for all loaded code ----
     * ARM64 I-cache and D-cache are not coherent. memcpy above writes
     * code to the D-cache, but the I-cache may hold stale data at these
     * addresses. While fresh mmap'd memory should have cold I-cache,
     * this is defensive — ensures correctness regardless of macOS
     * prefaulting or speculative instruction fetch behavior. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (elf_info.segments[i].flags & PF_X) {
                void *host_addr = (uint8_t *)g.host_base +
                                  elf_info.segments[i].gpa + elf_load_base;
                sys_icache_invalidate(host_addr, elf_info.segments[i].memsz);
            }
        }
    }
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (interp_info.segments[i].flags & PF_X) {
            void *host_addr = (uint8_t *)g.host_base +
                              interp_info.segments[i].gpa + interp_base;
            sys_icache_invalidate(host_addr, interp_info.segments[i].memsz);
        }
    }
    sys_icache_invalidate((uint8_t *)g.host_base + SHIM_BASE, shim_bin_len);

    /* ---- Step 5: Build page tables ---- */
    #define MAX_REGIONS 32
    mem_region_t regions[MAX_REGIONS];
    int nregions = 0;

    /* NOTE: Page table pool is NOT mapped in stage-1 page tables.
     * The MMU hardware walker accesses page tables through stage-2
     * translation (hv_vm_map RWX), so stage-1 mapping is unnecessary.
     * This avoids merging PT pool's RW perms with shim code's RX perms
     * in the same 2MB block, keeping the shim code block as RX. */

    /* Rosetta phase 1: load binary, set up VA aliases/kbuf, append
     * vDSO + rosetta segment regions for the page table builder. */
    /* Resolve ELF path early — needed by rosetta_prepare/finalize */
    char elf_realpath[LINUX_PATH_MAX];
    memset(elf_realpath, 0, sizeof(elf_realpath));
    if (!realpath(elf_path, elf_realpath))
        strncpy(elf_realpath, elf_path, sizeof(elf_realpath) - 1);

    if (need_rosetta) {
        if (rosetta_prepare(&g, elf_realpath, regions, &nregions,
                            MAX_REGIONS, verbose, &rr) < 0) {
            guest_destroy(&g);
            return 1;
        }
    }

    /* Shim code (RX) — sized to just cover the actual binary.
     * IMPORTANT: Apple HVF enforces W^X even with SCTLR.WXN=0.
     * This region must NOT overlap with any RW region in the same
     * 2MB block, or the merged RWX permissions will cause faults. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_BASE,
        .gpa_end   = SHIM_BASE + shim_bin_len,
        .perms     = MEM_PERM_RX
    };

    /* Shim data/stack (RW) */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = SHIM_DATA_BASE,
        .gpa_end   = SHIM_DATA_BASE + BLOCK_2MB,
        .perms     = MEM_PERM_RW
    };

    /* ELF segments: map each based on its p_flags.
     * For x86_64/rosetta mode, we skip pre-mapping binary segment PTEs.
     * Rosetta does its own mmap(MAP_FIXED) calls to set up the binary's
     * address space, which creates the correct page table entries. If we
     * pre-map here, the initial PROT_NONE reservation would need to
     * invalidate these entries — simpler to let Rosetta manage them.
     * The binary data is already loaded into host memory (elf_map_segments
     * above); PTEs are just not created until Rosetta's MAP_FIXED calls. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            if (nregions >= MAX_REGIONS) break;
            int perms = MEM_PERM_R;
            if (elf_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
            if (elf_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
            regions[nregions++] = (mem_region_t){
                .gpa_start = elf_info.segments[i].gpa + elf_load_base,
                .gpa_end   = elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                .perms     = perms
            };
        }
    }

    /* Interpreter segments (if dynamic linking) */
    for (int i = 0; i < interp_info.num_segments; i++) {
        if (nregions >= MAX_REGIONS) break;
        int perms = MEM_PERM_R;
        if (interp_info.segments[i].flags & PF_W) perms |= MEM_PERM_W;
        if (interp_info.segments[i].flags & PF_X) perms |= MEM_PERM_X;
        regions[nregions++] = (mem_region_t){
            .gpa_start = interp_info.segments[i].gpa + interp_base,
            .gpa_end   = interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
            .perms     = perms
        };
    }

    /* brk region (RW). The stack base is the hard upper bound so heap
     * growth cannot overwrite the guard page or live stack. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.brk_base,
        .gpa_end   = g.stack_base,
        .perms     = MEM_PERM_RW
    };

    /* Stack (RW) — position is dynamic (above brk) */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = g.stack_base,
        .gpa_end   = g.stack_top,
        .perms     = MEM_PERM_RW
    };

    /* mmap RX region (separate 2MB blocks for PROT_EXEC allocations).
     * Apple HVF enforces W^X on page table entries: a 2MB block can't be
     * both writable and executable. Shared library text (PROT_EXEC) goes
     * here, separate from RW data in the main mmap region. */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_RX_BASE,
        .gpa_end   = MMAP_RX_INITIAL_END,
        .perms     = MEM_PERM_RX
    };
    g.mmap_rx_end = MMAP_RX_INITIAL_END;

    /* mmap RW region (pre-mapped up to MMAP_INITIAL_END at 8GB+256MB).
     * Starts at 8GB to match real Linux kernel address space layout where
     * mmap regions are well above the program text/data/brk. Programs
     * may assume mmap returns high addresses (e.g. for pointer tagging
     * or address-space partitioning). Additional pages beyond
     * MMAP_INITIAL_END are mapped dynamically by
     * guest_extend_page_tables(). */
    if (nregions >= MAX_REGIONS) goto too_many_regions;
    regions[nregions++] = (mem_region_t){
        .gpa_start = MMAP_BASE,
        .gpa_end   = MMAP_INITIAL_END,
        .perms     = MEM_PERM_RW
    };
    g.mmap_end = MMAP_INITIAL_END;

    if (0) {
too_many_regions:
        fprintf(stderr, "hl: too many memory regions (%d >= %d)\n",
                nregions, MAX_REGIONS);
        guest_destroy(&g);
        return 1;
    }

    uint64_t ttbr0 = guest_build_page_tables(&g, regions, nregions);
    if (!ttbr0) {
        fprintf(stderr, "hl: failed to build page tables\n");
        guest_destroy(&g);
        return 1;
    }

    /* ---- Step 5b: Record semantic regions for /proc/self/maps ---- */
    guest_region_add(&g, SHIM_BASE, SHIM_BASE + shim_bin_len,
                     LINUX_PROT_READ | LINUX_PROT_EXEC, LINUX_MAP_PRIVATE,
                     0, "[shim]");
    guest_region_add(&g, SHIM_DATA_BASE, SHIM_DATA_BASE + BLOCK_2MB,
                     LINUX_PROT_READ | LINUX_PROT_WRITE, LINUX_MAP_PRIVATE,
                     0, "[shim-data]");

    /* In rosetta mode, do NOT register the x86_64 binary segments in
     * regions[]. Rosetta expects to reserve the binary's address range
     * via MAP_FIXED_NOREPLACE and then map the binary itself. */
    if (!need_rosetta) {
        for (int i = 0; i < elf_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (elf_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (elf_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g, elf_info.segments[i].gpa + elf_load_base,
                             elf_info.segments[i].gpa + elf_info.segments[i].memsz + elf_load_base,
                             prot, LINUX_MAP_PRIVATE,
                             elf_info.segments[i].offset, elf_realpath);
        }
    }

    /* Interpreter semantic regions (if dynamic linking) */
    if (interp_info.num_segments > 0) {
        char interp_resolved[LINUX_PATH_MAX];
        elf_resolve_interp(sysroot, elf_info.interp_path,
                       interp_resolved, sizeof(interp_resolved));

        for (int i = 0; i < interp_info.num_segments; i++) {
            int prot = LINUX_PROT_READ;
            if (interp_info.segments[i].flags & PF_W) prot |= LINUX_PROT_WRITE;
            if (interp_info.segments[i].flags & PF_X) prot |= LINUX_PROT_EXEC;
            guest_region_add(&g,
                             interp_info.segments[i].gpa + interp_base,
                             interp_info.segments[i].gpa + interp_info.segments[i].memsz + interp_base,
                             prot, LINUX_MAP_PRIVATE,
                             interp_info.segments[i].offset, interp_resolved);
        }
    }

    /* Heap starts at brk_base (initially empty, grows via sys_brk) */
    if (g.brk_base < g.brk_current) {
        guest_region_add(&g, g.brk_base, g.brk_current,
                         LINUX_PROT_READ | LINUX_PROT_WRITE,
                         LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                         0, "[heap]");
    }

    /* Stack guard page: PROT_NONE at bottom to catch overflow */
    guest_invalidate_ptes(&g, g.stack_base, g.stack_base + STACK_GUARD_SIZE);
    guest_region_add(&g, g.stack_base, g.stack_base + STACK_GUARD_SIZE,
                     LINUX_PROT_NONE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack-guard]");
    guest_region_add(&g, g.stack_base + STACK_GUARD_SIZE, g.stack_top,
                     LINUX_PROT_READ | LINUX_PROT_WRITE,
                     LINUX_MAP_PRIVATE | LINUX_MAP_ANONYMOUS,
                     0, "[stack]");

    /* Null guard page: invalidate page 0 so NULL dereferences produce
     * a translation fault (EC=0x20 → SIGSEGV) instead of executing
     * zero-initialized memory (UDF #0 → EC=0x00 → SIGILL). The shim
     * starts at SHIM_BASE=0x100000 but its 2MB L2 block covers 0x0–
     * 0x1FFFFF with RX permissions. Splitting into L3 pages and
     * invalidating page 0 matches Linux kernel behavior. */
    guest_invalidate_ptes(&g, 0, 0x1000);

    /* Harden the rest of block 0 against EL0 tampering: page-table pool
     * becomes EL1-only, [vvar] EL0 read-only, unused holes invalid. Writes
     * to the still-mapped [vvar]/[vdso]/shim pages are rejected by the
     * shim's block-0 permission-fault guard (see src/shim.S). */
    vdso_harden_low_block(&g);

    if (verbose) {
        fprintf(stderr, "hl: TTBR0=0x%llx, IPA base=0x%llx\n",
                (unsigned long long)ttbr0, (unsigned long long)g.ipa_base);

        /* Dump page table structure */
        uint64_t l0_off = ttbr0 - g.ipa_base;
        uint64_t *l0 = (uint64_t *)((uint8_t *)g.host_base + l0_off);
        unsigned l0i = (unsigned)(g.ipa_base / (512ULL * 1024 * 1024 * 1024));
        fprintf(stderr, "hl: L0[%u]=0x%llx\n", l0i,
                (unsigned long long)l0[l0i]);

        uint64_t l1_ipa = l0[l0i] & 0xFFFFFFFFF000ULL;
        uint64_t *l1 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l1_ipa - g.ipa_base));
        unsigned l1i = (unsigned)((g.ipa_base % (512ULL * 1024 * 1024 * 1024))
                                  / (1024ULL * 1024 * 1024));
        fprintf(stderr, "hl: L1[%u]=0x%llx\n", l1i,
                (unsigned long long)l1[l1i]);

        uint64_t l2_ipa = l1[l1i] & 0xFFFFFFFFF000ULL;
        uint64_t *l2 = (uint64_t *)((uint8_t *)g.host_base +
                                     (l2_ipa - g.ipa_base));
        for (int i = 0; i < 16; i++) {
            if (l2[i])
                fprintf(stderr, "hl: L2[%d]=0x%llx\n", i,
                        (unsigned long long)l2[i]);
        }
    }

    /* ---- Step 6: Build Linux initial stack ---- */
    syscall_init();
    proc_init();

    /* Record the absolute path of the hl binary itself so that
     * sub-processes (rosettad AOT translation) can invoke it. */
    {
        char self_path[LINUX_PATH_MAX];
        uint32_t path_len = sizeof(self_path);
        if (_NSGetExecutablePath(self_path, &path_len) == 0)
            proc_set_hl_path(self_path);
    }

    proc_set_shim(shim_bin, shim_bin_len);
    if (!need_rosetta)
        proc_set_elf_path(elf_path);
    if (sysroot)
        proc_set_sysroot(sysroot);
    extern char **environ;

    /* Build guest environ: start from host environ, then override keys
     * that must be guest-visible paths under rooted VFS / Linux X11. */
    const char **guest_env = (const char **)environ;
    char **guest_env_owned = NULL;
    char *owned_env_vars[24];
    int n_owned_env = 0;
    memset(owned_env_vars, 0, sizeof(owned_env_vars));
    const int owned_env_cap = 24;

    /* LD_LIBRARY_PATH: sysroot libs for dynamic linker soname search. */
    if (sysroot && sysroot[0] && n_owned_env < 16) {
        const char *libdir = (hl_vfs_mode() == HL_FS_ROOTED)
            ? "/sysroot/lib" : NULL;
        char libdir_host[LINUX_PATH_MAX];
        if (!libdir) {
            snprintf(libdir_host, sizeof(libdir_host), "%s/lib", sysroot);
            libdir = libdir_host;
        }
        const char *old_ld = getenv("LD_LIBRARY_PATH");
        size_t n = strlen(libdir) + 1 + 17 +
                   (old_ld && old_ld[0] ? strlen(old_ld) + 1 : 0);
        char *s = malloc(n);
        if (s) {
            if (old_ld && old_ld[0])
                snprintf(s, n, "LD_LIBRARY_PATH=%s:%s", libdir, old_ld);
            else
                snprintf(s, n, "LD_LIBRARY_PATH=%s", libdir);
            owned_env_vars[n_owned_env++] = s;
            if (verbose)
                fprintf(stderr, "hl: guest %s\n", s);
        }
    }

    /*
     * Guest-only LD_PRELOAD (does not affect host/macOS dyld).
     * Used to force Xlib PutImage path when MIT-SHM cannot attach
     * guest SysV segments into host XQuartz (see libno_xshm).
     * HL_GUEST_LD_PRELOAD=/guest/path.so
     */
    if (n_owned_env < 16) {
        const char *gpl = getenv("HL_GUEST_LD_PRELOAD");
        if (gpl && gpl[0]) {
            size_t n = strlen(gpl) + 12;
            char *s = malloc(n);
            if (s) {
                snprintf(s, n, "LD_PRELOAD=%s", gpl);
                owned_env_vars[n_owned_env++] = s;
                if (verbose)
                    fprintf(stderr, "hl: guest %s\n", s);
            }
        }
    }

    /* HOME: any explicit or implicit /home/user bind is a guest-visible home,
     * including under --isolated (which disables defaults, not explicit
     * binds). */
    if (home_bind_set && n_owned_env < 16) {
        { char *e = strdup("HOME=/home/user");
          if (e) owned_env_vars[n_owned_env++] = e; }
    }

    /* XAUTHORITY: only propagate the implicit host profile. Under --isolated,
     * an explicit /home/user bind need not contain the host cookie file. */
    if (!isolated && home_bind_set) {
        const char *host_home = getenv("HOME");
        if (host_home && host_home[0] && n_owned_env < 16) {
            char xauth_host[LINUX_PATH_MAX];
            snprintf(xauth_host, sizeof(xauth_host), "%s/.Xauthority",
                     host_home);
            if (access(xauth_host, R_OK) == 0) {
                char *e = strdup("XAUTHORITY=/home/user/.Xauthority");
                if (e) owned_env_vars[n_owned_env++] = e;
            }
        }
    }

    /* DISPLAY: Linux Xlib wants :N (→ /tmp/.X11-unix/XN), not the
     * XQuartz launchd absolute path. Prefer host :N if already set. */
    if (x11_socket_bound && n_owned_env < 16) {
        const char *host_dpy = getenv("DISPLAY");
        const char *guest_dpy = ":0";
        if (host_dpy && host_dpy[0] == ':' && host_dpy[1] >= '0' &&
            host_dpy[1] <= '9')
            guest_dpy = host_dpy;
        size_t n = strlen(guest_dpy) + 9;
        char *s = malloc(n);
        if (s) {
            snprintf(s, n, "DISPLAY=%s", guest_dpy);
            owned_env_vars[n_owned_env++] = s;
            if (verbose)
                fprintf(stderr, "hl: guest %s (X11 socket bridged)\n", s);
        }
    }

    /* TMPDIR: force /tmp when bound — host macOS TMPDIR is under
     * /var/folders and is not visible in the guest. XMMS puts its
     * control socket at $TMPDIR/xmms_user.0. */
    if (tmp_bound && n_owned_env < 16) {
        { char *e = strdup("TMPDIR=/tmp");
          if (e) owned_env_vars[n_owned_env++] = e; }
        if (n_owned_env < 16)
            { char *e = strdup("TMP=/tmp");
              if (e) owned_env_vars[n_owned_env++] = e; }
    }

    /*
     * Optional G1 HyperLinux-macOS GTK+ 1.2 theme (dialogs/menus only —
     * not XMMS player skins). Default OFF: stock Motif-like GTK1 look.
     *
     * Enable with HL_GTK_THEME=1 (sysroot gtkrc + hlflat engine) or
     * HL_GTK_RC=/path/to/gtkrc. User ~/.gtkrc / ~/.xmms/gtkrc still apply
     * if present.
     *
     * Fonts: GTK1 uses core X fonts (XLFD). Server FontPath is set by
     * launch scripts (x11-fontpath.sh); FONTCONFIG is dormant for GTK1.
     */
    {
        const char *gtk_theme = getenv("HL_GTK_THEME");
        const char *override = getenv("HL_GTK_RC");
        int want_theme = 0;
        if (override && override[0] && access(override, R_OK) == 0)
            want_theme = 1;
        else if (gtk_theme && gtk_theme[0] == '1' && gtk_theme[1] == '\0')
            want_theme = 1;
        else if (gtk_theme && (strcmp(gtk_theme, "on") == 0 ||
                               strcmp(gtk_theme, "yes") == 0))
            want_theme = 1;

        if (want_theme && n_owned_env < owned_env_cap) {
            char host_rc[LINUX_PATH_MAX];
            const char *guest_rc = NULL;
            host_rc[0] = '\0';
            if (override && override[0] && access(override, R_OK) == 0) {
                size_t n = strlen(override) + 14; /* "GTK_RC_FILES=" + NUL */
                char *s = malloc(n);
                if (s) {
                    snprintf(s, n, "GTK_RC_FILES=%s", override);
                    owned_env_vars[n_owned_env++] = s;
                    if (verbose)
                        fprintf(stderr, "hl: guest %s (HL_GTK_RC)\n", s);
                }
            } else if (sysroot && sysroot[0]) {
                snprintf(host_rc, sizeof(host_rc),
                         "%s/share/themes/HyperLinux-macOS/gtk-1.2/gtkrc",
                         sysroot);
                if (access(host_rc, R_OK) == 0) {
                    if (hl_vfs_mode() == HL_FS_ROOTED)
                        guest_rc =
                            "/sysroot/share/themes/HyperLinux-macOS/gtk-1.2/"
                            "gtkrc";
                    else
                        guest_rc = host_rc;
                    size_t n = strlen(guest_rc) + 14;
                    char *s = malloc(n);
                    if (s) {
                        snprintf(s, n, "GTK_RC_FILES=%s", guest_rc);
                        owned_env_vars[n_owned_env++] = s;
                        if (verbose)
                            fprintf(stderr, "hl: guest %s\n", s);
                    }
                }
            }
        } else if (verbose) {
            fprintf(stderr,
                    "hl: stock GTK theme (set HL_GTK_THEME=1 for "
                    "HyperLinux-macOS)\n");
        }
    }

    /*
     * X11 locale files (XSupportsLocale / XCreateFontSet). Without these,
     * Gdk warns "locale not supported by C library" when host LANG is
     * UTF-8 and libX11 cannot open its locale tree under the guest.
     */
    if (sysroot && sysroot[0] && n_owned_env < owned_env_cap) {
        char host_loc[LINUX_PATH_MAX];
        snprintf(host_loc, sizeof(host_loc), "%s/share/X11/locale", sysroot);
        if (access(host_loc, R_OK) == 0) {
            const char *guest_loc = (hl_vfs_mode() == HL_FS_ROOTED)
                ? "/sysroot/share/X11/locale"
                : host_loc;
            size_t n = strlen(guest_loc) + 12;
            char *s = malloc(n);
            if (s) {
                snprintf(s, n, "XLOCALEDIR=%s", guest_loc);
                owned_env_vars[n_owned_env++] = s;
                if (verbose)
                    fprintf(stderr, "hl: guest %s\n", s);
            }
        }
    }

    /*
     * GTK theme engines (hlflat): only when HyperLinux theme is enabled.
     * Engines load from $GTK_EXE_PREFIX/lib/gtk/themes/engines.
     */
    {
        const char *gtk_theme = getenv("HL_GTK_THEME");
        const char *override = getenv("HL_GTK_RC");
        int want_theme = 0;
        if (override && override[0])
            want_theme = 1;
        else if (gtk_theme && (gtk_theme[0] == '1' ||
                               strcmp(gtk_theme, "on") == 0 ||
                               strcmp(gtk_theme, "yes") == 0))
            want_theme = 1;
        if (want_theme && sysroot && sysroot[0] &&
            n_owned_env < owned_env_cap) {
            char host_eng[LINUX_PATH_MAX];
            snprintf(host_eng, sizeof(host_eng),
                     "%s/lib/gtk/themes/engines/libhlflat.so", sysroot);
            if (access(host_eng, R_OK) == 0) {
                const char *pfx = (hl_vfs_mode() == HL_FS_ROOTED)
                    ? "/sysroot" : sysroot;
                size_t n = strlen(pfx) + 16; /* "GTK_EXE_PREFIX=" + NUL */
                char *s = malloc(n);
                if (s) {
                    snprintf(s, n, "GTK_EXE_PREFIX=%s", pfx);
                    owned_env_vars[n_owned_env++] = s;
                    if (verbose)
                        fprintf(stderr, "hl: guest %s (theme engines)\n", s);
                }
            }
        }
    }

    /*
     * Prefer a locale glibc always knows when host LANG is exotic to the
     * guest (macOS en_US.UTF-8 with incomplete guest locale-archive).
     * HL_GUEST_LANG overrides. C.UTF-8 if present in glibc; else C.
     * Does not force LC_ALL so apps can still set categories.
     */
    if (n_owned_env < owned_env_cap && !getenv("HL_GUEST_LANG_OFF")) {
        const char *gl = getenv("HL_GUEST_LANG");
        if (!gl || !gl[0])
            gl = "C.UTF-8";
        size_t n = strlen(gl) + 6;
        char *s = malloc(n);
        if (s) {
            snprintf(s, n, "LANG=%s", gl);
            owned_env_vars[n_owned_env++] = s;
            if (verbose)
                fprintf(stderr, "hl: guest %s\n", s);
        }
    }

    if (n_owned_env > 0) {
        int envc = 0;
        while (environ[envc]) envc++;
        guest_env_owned = calloc((size_t)envc + (size_t)n_owned_env + 1,
                                 sizeof(char *));
        if (guest_env_owned) {
            int j = 0;
            for (int k = 0; k < n_owned_env; k++)
                guest_env_owned[j++] = owned_env_vars[k];
            for (int i = 0; i < envc; i++) {
                /* Drop keys we override. */
                int skip = 0;
                for (int k = 0; k < n_owned_env; k++) {
                    const char *ov = owned_env_vars[k];
                    const char *eq = strchr(ov, '=');
                    if (!eq) continue;
                    size_t keylen = (size_t)(eq - ov) + 1; /* include '=' */
                    if (strncmp(environ[i], ov, keylen) == 0) {
                        skip = 1;
                        break;
                    }
                }
                if (!skip)
                    guest_env_owned[j++] = environ[i];
            }
            guest_env_owned[j] = NULL;
            guest_env = (const char **)guest_env_owned;
        }
    }

    uint64_t sp;
    uint64_t entry_point;

    /* ---- Step 7: Create vCPU and configure registers ---- */
    hv_vcpu_t vcpu;
    hv_vcpu_exit_t *vexit;
    HV_CHECK(hv_vcpu_create(&vcpu, &vexit, NULL));
    g.vcpu = vcpu;
    g.exit = vexit;
    g.vcpu_valid = 1;

    if (need_rosetta) {
        /* Rosetta phase 2: kbuf dual-mapping, vDSO, fd 3, argv, proc state.
         * Needs vcpu handle for TCR_EL1/TTBR1_EL1 sysreg writes.
         * Pass elf_path (not elf_realpath) so multi-call binaries (e.g.
         * symlinks echo→coreutils) see the correct argv[0]. open() and
         * rosettad both follow symlinks, so the original path works. */
        int rosetta_argc;
        const char **rosetta_argv;
        uint64_t vdso_addr;
        if (rosetta_finalize(&g, vcpu, elf_path,
                             guest_argc, guest_argv, &rr, verbose,
                             &rosetta_argc, &rosetta_argv, &vdso_addr) < 0) {
            guest_destroy(&g);
            return 1;
        }
        vdso_publisher_start(&g);

        /* Stack auxv describes rosetta as the main binary (binfmt_misc
         * semantics: AT_PHDR/PHENT/PHNUM/ENTRY all refer to rosetta). */
        sp = build_linux_stack(&g, g.stack_top,
                               rosetta_argc, rosetta_argv,
                               guest_env, &rr.rosetta_info,
                               0 /* rosetta is ET_EXEC at link addr */,
                               0 /* no dynamic linker for rosetta */,
                               vdso_addr,
                               3 /* AT_EXECFD: binary pre-opened at fd 3 */);
        free((void *)rosetta_argv);
        if (sp == 0) {
            fprintf(stderr, "hl: failed to build initial stack\n");
            vdso_publisher_stop();
            guest_destroy(&g);
            return 1;
        }
        entry_point = rr.entry_point;
    } else {
        /* Normal aarch64 mode */
        proc_set_cmdline(guest_argc, guest_argv);

        /* Build vDSO: real gettimeofday/clock_gettime via [vvar], plus
         * rt_sigreturn trampoline for sa_restorer==0. */
        uint64_t native_vdso = vdso_build(&g);
        if (!native_vdso) {
            fprintf(stderr, "hl: failed to build vDSO\n");
            free(guest_env_owned);
            for (int k = 0; k < n_owned_env; k++)
                free(owned_env_vars[k]);
            guest_destroy(&g);
            return 1;
        }
        vdso_publisher_start(&g);

        sp = build_linux_stack(&g, g.stack_top,
                               guest_argc, guest_argv,
                               guest_env, &elf_info,
                               elf_load_base, interp_base,
                               native_vdso,
                               -1 /* no AT_EXECFD */);
        if (sp == 0) {
            fprintf(stderr, "hl: failed to build initial stack\n");
            free(guest_env_owned);
            for (int k = 0; k < n_owned_env; k++)
                free(owned_env_vars[k]);
            vdso_publisher_stop();
            guest_destroy(&g);
            return 1;
        }

        /* Entry point: interpreter entry if dynamic, ELF entry if static. */
        entry_point = (interp_base != 0)
            ? (interp_info.entry + interp_base)
            : (elf_info.entry + elf_load_base);
    }

    /* guest_env strings were copied into guest memory by build_linux_stack;
     * free the pointer array only. Owned override strings can be freed too. */
    free(guest_env_owned);
    for (int k = 0; k < n_owned_env; k++)
        free(owned_env_vars[k]);

    if (verbose)
        fprintf(stderr, "hl: SP=0x%llx, entry=0x%llx%s\n",
                (unsigned long long)sp,
                (unsigned long long)entry_point,
                need_rosetta ? " (via rosetta)" :
                interp_base ? " (via interpreter)" : "");

    /* All guest-visible addresses are IPA-based: GUEST_IPA_BASE + offset */
    uint64_t shim_ipa  = guest_ipa(&g, SHIM_BASE);
    uint64_t entry_ipa = guest_ipa(&g, entry_point);
    uint64_t sp_ipa    = guest_ipa(&g, sp);
    uint64_t el1_sp    = guest_ipa(&g, SHIM_DATA_BASE + BLOCK_2MB);

    /* Register main thread in the thread table (before entering run loop) */
    thread_register_main(vcpu, vexit, proc_get_pid(), el1_sp);

    /* -- System registers (set from host; MMU enable deferred to HVC #4) -- */

    /* VBAR_EL1: vector table at shim_base + 0x800 (.align 11 offset) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_VBAR_EL1,
                                 shim_ipa + 0x800));

    /* MAIR_EL1: Attr0=Device-nGnRnE (0x00), Attr1=Normal WB (0xFF) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_MAIR_EL1, 0xFF00));

    /* TCR_EL1: 4KB granule, 48-bit VA.
     * When kernel VA buffer is active (rosetta mode), enable TTBR1 walks
     * (EPD1=0) so kernel-space addresses are translated via TTBR1. */
    uint64_t tcr_value = g.kbuf_base ? TCR_EL1_VALUE_KBUF : TCR_EL1_VALUE;
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TCR_EL1, tcr_value));

    /* TTBR0_EL1: page table base (IPA from guest_build_page_tables) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR0_EL1, ttbr0));

    /* TTBR1_EL1: kernel VA page tables (rosetta mode) or unused */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_TTBR1_EL1,
                                  g.ttbr1 ? g.ttbr1 : 0));

    /* CPACR_EL1: enable FP/SIMD at EL0 and EL1 (FPEN=0b11) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_CPACR_EL1, 3ULL << 20));

    /* ELR_EL1: EL0 entry point (shim will ERET to this address) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_ELR_EL1, entry_ipa));

    /* SPSR_EL1: EL0t, AArch64, all interrupts masked on entry */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SPSR_EL1, 0x0));

    /* SP_EL0: initial stack pointer for EL0 */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL0, sp_ipa));

    /* SP_EL1: EL1 stack for exception handlers (top of shim data region) */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SP_EL1, el1_sp));

    /* SCTLR_EL1: read default, then enable MMU + caches */
    uint64_t sctlr;
    HV_CHECK(hv_vcpu_get_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, &sctlr));
    if (verbose)
        fprintf(stderr, "hl: SCTLR_EL1 default=0x%llx\n",
                (unsigned long long)sctlr);

    /* Build a proper SCTLR with RES1 bits + caches, but WITHOUT MMU enable.
     * Apple's HVF requires the MMU to be enabled DURING vCPU execution
     * (via HVC #4 from the shim), not before hv_vcpu_run. Setting SCTLR.M=1
     * via hv_vcpu_set_sys_reg before start causes permission faults.
     * The shim will HVC #4 to enable M after TLBI/DSB/ISB. */
    sctlr = SCTLR_RES1 | SCTLR_C | SCTLR_I
          | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;  /* No SCTLR_M here */
    HV_CHECK(hv_vcpu_set_sys_reg(vcpu, HV_SYS_REG_SCTLR_EL1, sctlr));

    /* -- General purpose registers -- */

    /* PC = shim entry (TLBI + zero regs + ERET) */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_PC, shim_ipa));

    /* CPSR = EL1h (0x3c5) — shim runs at EL1 */
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_CPSR, 0x3c5));

    /* Zero all general purpose registers */
    for (int i = 0; i < 31; i++) {
        HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0 + i, 0));
    }

    /* Pass the full SCTLR value (WITH M=1) in X0 for the shim to
     * enable the MMU during execution via HVC #4. */
    uint64_t sctlr_with_mmu = SCTLR_RES1 | SCTLR_M | SCTLR_C | SCTLR_I
                            | SCTLR_DZE | SCTLR_UCT | SCTLR_UCI;
    HV_CHECK(hv_vcpu_set_reg(vcpu, HV_REG_X0, sctlr_with_mmu));

    if (verbose) {
        fprintf(stderr, "hl: vCPU configured: PC=0x%llx SCTLR=0x%llx "
                "VBAR=0x%llx TTBR0=0x%llx TCR=0x%llx\n",
                (unsigned long long)shim_ipa,
                (unsigned long long)sctlr,
                (unsigned long long)(shim_ipa + 0x800),
                (unsigned long long)ttbr0,
                (unsigned long long)tcr_value);
        fprintf(stderr, "hl: ELR_EL1=0x%llx SP_EL0=0x%llx SP_EL1=0x%llx\n",
                (unsigned long long)entry_ipa,
                (unsigned long long)sp_ipa,
                (unsigned long long)el1_sp);
    }

    /* ---- Step 7b: Initialize GDB stub (if requested) ---- */
    if (gdb_port > 0 && !need_rosetta) {
        if (gdb_stub_init(gdb_port, &g) < 0) {
            fprintf(stderr, "hl: failed to initialize GDB stub\n");
            guest_destroy(&g);
            return 1;
        }
        /* Program debug registers on the initial vCPU */
        gdb_stub_sync_debug_regs(vcpu);

        if (gdb_stop_on_entry)
            gdb_stub_wait_for_attach();
    } else if (gdb_port > 0 && need_rosetta) {
        fprintf(stderr, "hl: --gdb is not supported for x86_64/rosetta "
                "binaries (JIT makes source-level debugging meaningless)\n");
    }

    /* ---- Step 8: vCPU execution loop ---- */
    int exit_code = vcpu_run_loop(vcpu, vexit, &g, verbose, timeout_sec, 1 /* main */);

    /* ---- Cleanup ---- */
    vdso_publisher_stop();
    gdb_stub_shutdown();
    guest_destroy(&g);

    return exit_code;
}
